### ISSUE TITLE
Coverbilleder på resultatvisning skal have en maxhøjde

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo#100]
F.eks. på [denne søgning](https://biblo.dk/find?q=fr%C3%B8ken%20ignora&emneord=&materialer=) er det nødvendigt at billederne får en makshøjde

**Comment by hrmoller** [comment]
Løses i forbindelse med #86

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
