### ISSUE TITLE
Styling af søgefeltet fejler iøbjelikket

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#105]
Jeg tror at det ser sket efter at der er rykket rundt på susy .

![skaermbillede 2016-06-08 kl 10 26 10](https://cloud.githubusercontent.com/assets/15238/15891421/adf7b7f0-2d74-11e6-92d4-39facb95cf38.png)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
