### ISSUE TITLE
Grid'et for anmeldelser på værksiden  skal justeres.

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#106]
Flere spans . (som introduceret i #84)
 
![skaermbillede 2016-06-08 kl 10 28 33](https://cloud.githubusercontent.com/assets/15238/15891482/fffadc58-2d74-11e6-8cf4-2f9dc908c3fd.png)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
