### ISSUE TITLE
I FF: Footeren er meget tæt på den nederste anmeldelse

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#108]
På min anmeldelsesside er footerbjælken helt tæt på den nederste anmeldelse. Det ser ikke så godt ud.
![footer](https://cloud.githubusercontent.com/assets/1375270/15925579/ffd53fd4-2e37-11e6-9d8b-49660fba5b1a.jpg)

**Comment by fvsdbc** [comment]
Ikke i min FF - har du stadig problemet?

**Comment by AndersFriisBrodsgaard** [comment]
@Mariannedybkjaer Kan jeg ikke få dig til at kigge på denne her igen?

**Comment by Mariannedybkjaer** [comment]
Synes stadig godt der kunne være et par pixels mere luft. Men det er nok en smagssag :-)

**Comment by fvsdbc** [comment]
Har fået lidt mere luft ...

**Comment by KiraH** [comment]
testet OK
