### ISSUE TITLE
Ved indsæt anmeldelse under opret indlæg/kommentar i gruppe ser man kun boganmeldelser

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#112]
Man skal kunne se anmeldelser af alle materialetyper

**Comment by jacobandresen** [comment]
jeg tror at den er fixet med #111 ?

**Comment by jacobandresen** [comment]
Den her er iøjeblikket ikke på listen over anmelder jeg kan sætte ind i en gruppe på biblo-dev https://biblo-dev.demo.dbc.dk/anmeldelse/69   (film)  ... mens den her er : https://biblo-dev.demo.dbc.dk/anmeldelse/70 (musik)

**Comment by KiraH** [comment]
spilanmeldelse man ikke kan se: https://biblo-dev.demo.dbc.dk/anmeldelse/71
filmanmeldelse man ikke kan se: https://biblo-dev.demo.dbc.dk/anmeldelse/68

**Comment by jacobandresen** [comment]
Det ser ud til at kravene til metadata for de anmeldte materialer ikke bliver mødt lige nu. Det ser ud til at der er nogle issues vedr.  creator lige nu.  Jeg løsner kravene lidt så der kun kræves dcTitle  (og ikke nødvendigvis creator)

**Comment by jacobandresen** [comment]
Jeg kan nu indsætte "Winky's Hest" .https://biblo-dev.demo.dbc.dk/grupper/1#!

**Comment by jacobandresen** [comment]
Issues vedr. creator kan evt løses i #117  .

**Comment by KiraH** [comment]
Testet OK
