### ISSUE TITLE
Visning af anmeldelse fejler i styling i indlæg

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#115]
Når man har indsat en anmeldelse i et indlæg, skæres teksten fra anmeldelsen ikke af, hvis anmeldelsen er lang. Det skal den, så den holder sig over knappen "Se hele anmeldelsen".
![screenshot 2016-06-10 12 58 24](https://cloud.githubusercontent.com/assets/18284484/15962434/48fc4abc-2f0b-11e6-83e8-5badb1173c9a.png)

**Comment by jacobandresen** [comment]
Hej @hrmoller ! Jeg tror at jeg har udbedret det Anders bemærkede .  Kan du lige kaste et blik på , hvordan det spiller sammen med visningen ovre på profil siden? Jeg bemærker at der stadigvæk er et issue med visning af titel her (der kunne måske komme en text-overflow: ellipsis på .. ?)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
