### ISSUE TITLE
Der vises forkert forfatternavn på nogle poster

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#117]
Det er ind imellem illustratorens navn, der står under titlen på en værkside. Det skal være forfatterens navn. Det skyldes sandsynligvis, at vi henter det forkerte felt ud i forbindelse med visningen af værket.
Ex https://biblo.dk/materiale/870970-basis:27423744

**Comment by AndersFriisBrodsgaard** [comment]
Det ser ud til, at der skal vises "creatorAut" i stedet for "creator", hvis "creatorAut" findes.

**Comment by KiraH** [comment]
testet OK
