### ISSUE TITLE
Videoanmeldelser kan ikke afvikles

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#118]
De videoanmeldelser, der uploades på biblo.dk kan ikke afvikles efterfølgende. 
På værksiden og anmeldelsessiden vises det midlertidige billede https://biblo.dk/anmeldelse/64718
På profilsiden under anmeldelser vises en thumbnail https://biblo.dk/profil/44058#ANMELDELSER

**Comment by jacobandresen** [comment]
Jeg har lige forsøgt mig med at uploaded en video til gruppe 3 på produktion lige nu her : https://biblo.dk/grupper/3  . 

Jeg skrev flg ledetekst:  "test video fra Jacob (Jeg hijacker lige tråden til test af video ...) " 

LIge nu ser det ud til at skaleringen ikke virker der heller .


Jeg bemærker at det virker som tilsigtet fra biblo-demo lige nu. https://biblo.demo.dbc.dk/anmeldelse/38

**Comment by jacobandresen** [comment]
Christian har gjort mig opmærksom på at der er rettet et issue i ha-proxyen foran biblo. Det burde udbedre problemet fremadrettet.

**Comment by jacobandresen** [comment]
Hej @hyatt03  . Kan du afspille sns notifikationerne fra amazon på de videoer der ikke modtog skaleringsinfo  ?

**Comment by jacobandresen** [comment]
Jeg kan se videoerne nu.

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
