### ISSUE TITLE
Visning af 2 anmeldelser af samme bog under profil giver "Henter data"

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#119]
... og "Se hele anmeldelsen" linker til en tom side. Brugeren har lavet to anmeldelser af samme bog, og den nyeste vises korrekt, mens den ældste anmeldelse ikke gør.
Se nederste anmeldelse for denne bruger:
https://biblo.dk/profil/12783#ANMELDELSER
Den ældste anmeldelse skal ikke vises.

**Comment by jacobandresen** [comment]
Den her tænker jeg er relateret til #104 ..?

**Comment by AndersFriisBrodsgaard** [comment]
Og måske også relateret til #136

**Comment by AndersFriisBrodsgaard** [comment]
Samme fejl sker på denne profil: https://biblo.dk/profil/22034

**Comment by hrmoller** [comment]
Materialet findes ikke i brønden - pid: 870970-basis:3486501
Ud fra hvad @fvsdbc og jeg lige kan se hedder den Percy Jackson - Lyntyven og har et ID der begynder med 150015-forlag.

Mit gæt er at det er et materiale der kom i pallesgavebod.dk mere eller mindre manuelt og derefter er det blevet til en pid da vi migrerede til Biblo, men til en pid der ikke findes.
Der er iøvrigt 21 anmeldelser der matcher pid'en hvoraf de nyeste er fra august '14.

**Comment by hrmoller** [comment]
I forhold til @AndersFriisBrodsgaard's kommentar den 22. aug er det `870970-basis:3593551` det drejer sig om men igen findes pid'en ikke i brønden.

**Comment by AndersFriisBrodsgaard** [comment]
Det ser ud til at være et problem, der er relateret til migrering af anmeldelser fra PG. Lukker derfor.
