### ISSUE TITLE
Får vist forkert tid til aflevering under beskeder i profilen

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#128]
Jeg får at vide, at der er 1 dag til jeg skal aflevere, men der er to dage til. 
Dato: 23. juni, afleveringsdato ifølge openUserStatus: 25. juni.
Se dump og respons fra openUserStatus:
`<ous:loan>
<ous:author/>
<ous:title>Hugo / directed by Martin Scorsese. - 1</ous:title>
<ous:dateDue>2016-06-25T00:00:00+02:00</ous:dateDue>
<ous:loanId>4860558756</ous:loanId>
<ous:reminderLevel>1</ous:reminderLevel>
</ous:loan>`

Kan det have noget at gøre med tidszoner og de + 2 timer? Mener at det tidligere har givet problemer på Palles. 
![screenshot 2016-06-23 13 45 01](https://cloud.githubusercontent.com/assets/18284484/16301972/bdee3578-3948-11e6-94d9-762757bfea82.png)

**Comment by AndersFriisBrodsgaard** [comment]
Note: Det blev vist korrekt tidligere i dag.

**Comment by AndersFriisBrodsgaard** [comment]
@Mariannedybkjaer har du mulighed for at teste den her? Jeg har ikke noget, der skal afleveres lige om lidt. Test helst på biblo-dev.

**Comment by Mariannedybkjaer** [comment]
Jeg har en bog, der skal afleveres i dag. Den vises ikke - hverken på biblo.demo eller biblo.dev. Eller i drift.

**Comment by Mariannedybkjaer** [comment]
Bogen - Den første sten - var på min liste over notifikationer i går. Da stod der at "den skal afleveres senest i dag" - 6.9.  Men den skulle først afleveres senest i dag 7.9. Og i dag er den væk fra listen. Og endnu ikke afleveret.
