### ISSUE TITLE
Emojis i brugernavn vises ikke i default-teksten under "Anmeldelser" og "Aktivitet" i profilen

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#129]
Se dump for brugeren Valdemar...
https://biblo.dk/profil/46174#ANMELDELSER

![screenshot 2016-06-23 14 53 07](https://cloud.githubusercontent.com/assets/18284484/16303748/a977f5a2-3952-11e6-9a20-10067f54a71b.png)

**Comment by KiraH** [comment]
testet OK
