### ISSUE TITLE
liste i biblo-admin over flaggede indlæg 

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#13]
jeg mener vi talte om at behandlede flags på listen i admin skulle markeres som læst/behandlet, ikke slettes som det sker nu. Vi vil gerne have mulighed for at tjekke historikken, om en bruger har gjort noget lignende før. Det skal så vurderes hvor stort det bliver at ændre, udvide. Om det kan nås i fase 2 osv.

**Comment by kasperg** [comment]
Flag bliver ikke slettet - [de bliver markeret som læst](https://github.com/DBCDK/biblo-admin/blob/develop/web/modules/custom/dbcdk_community/src/Form/FlagsMarkReadForm.php#L97). 

Det kan  opleves som om flagene bliver slettet, da læste flags optræder ikke i oversigten. Det er nu med vilje, da listen repræsenterer indhold som moderatorerne skal tage aktivt stilling til.

Den model mener jeg stadig er værd at beholde, men hvis vi vil give mulighed for at checke historikken, så kunne vi på brugerens profil vise en liste over alle brugerens indlæg, som der er blevet rejst flag imod, på samme måde som vi på nuværende tidspunkt viser karantæner.

**Comment by kkdbc** [comment]
tak for præcisering, jeg tror det bliver et nødvendigt krav mht. foreslåede løsning. Prioritering taler vi om.
