### ISSUE TITLE
Fejl 500 på søgninger med æ ø å

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo#130]
Søgninger der er indeholder æ ø å resultere i en fejl 500

F.eks. https://biblo.dk/find?q=Gås&emneord=&materialer=

**Comment by jacobandresen** [comment]
https://github.com/DBCDK/biblo/commit/e3501758277c3b93967b45163ad24c65b9bf84cb

https://biblo.demo.dbc.dk/find?q=g%C3%A5s&emneord=&materialer=

**Comment by jacobandresen** [comment]
fixet på community client https://github.com/DBCDK/dbc-node-community-client/commit/5a0218159b258adec71aabd2dccfbba65ae1285d
