### ISSUE TITLE
Der mangler styling af anmeldelser indsat som kommentar i en gruppe

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#131]
Anmeldelser, der er indsat som kommentarer i grupper, skal styles som anmeldelser, der er indsat som indlæg i grupper. 
Se fx indlæg af Anders den Røde med anmeldelse af "Vinden i piletræerne" og efterfølgende kommentar med samme anmeldelse:
https://biblo.demo.dbc.dk/grupper/1

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard kan du ikke uddybe hvad der mangler efter i kombi med noget design hejs på droppen?

**Comment by AndersFriisBrodsgaard** [comment]
Lukkes. Det skal ikke være muligt at tilføje anmeldelse til kommentarer.
