### ISSUE TITLE
Gruppebilleder i søgeresultatsiden har forkert format

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#132]
De skal være kvadratiske som de er på "grupper"-siden og øverst på selve gruppens side. Og de skal ikke skaleres skævt.

![screenshot 2016-06-28 10 39 35](https://cloud.githubusercontent.com/assets/18284484/16409203/a7b1511e-3d1c-11e6-941d-216f18808bf9.png)

**Comment by fvsdbc** [comment]
Billedet med våbenskjoldet er markant anderledes end de andre. Åbner man det - https://biblo.dk/billede/632/small-square - lander man på en side fra cloudfront.net. Endvidere er det ikke kvadratisk, som de andre.

**Comment by AndersFriisBrodsgaard** [comment]
Der er oprettet et nyt issue, der fikser denne problematik. #251
