### ISSUE TITLE
firefox: bullets fra listevisning vises i søgeresultat

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#134]
På søgeresultat i hhv biblioteksmaterialer og grupper ses en prik i firefox. ok i chrome

![bullets_ff](https://cloud.githubusercontent.com/assets/18323273/16488866/f78a8784-3ed2-11e6-9d0d-538916e30a79.png)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
