### ISSUE TITLE
Bruger får UPS-fejl v login

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#135]
En bruger får en fejlside med "UPS siden findes ikke", når hun logger ind. AFB og jeg har efterprøvet det og får samme resultat. Hendes brugerid er frejxxxx

**Comment by Mariannedybkjaer** [comment]
Der er kommet endnu en henvendelse om dette problem. Fra Nanne Højborg, nhojborg@gmail.com

**Comment by AndersFriisBrodsgaard** [comment]
@Mariannedybkjaer vil du teste igen - eller har du hørt fra brugeren?
