### ISSUE TITLE
Bruger har kunnet lave to anmeldelser af samme materiale

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#136]
Brugeren Bellamax har lavet to anmeldelser af bogen "Emmy - goth nytår":
https://biblo.dk/materiale/870970-basis:27557880
https://biblo.dk/profil/43746
Det skal kun være muligt at lave én anmeldelse af et værk.

**Comment by AndersFriisBrodsgaard** [comment]
Der skal tjekkes ved klik på "OK", om brugeren allerede har lavet en anmeldelse. Hvis han har, så vises et modalvindue, hvor brugeren skal vælge at overskrive den gamle anmeldelse eller beholde den gamle anmeldelse.

**Comment by KiraH** [comment]
testet OK
