### ISSUE TITLE
Moderator kan ikke skrive ny anmeldelse eller rette i anmeldelse udenfor åbningstid

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#139]
Moderator skal kunne redigere anmeldelser og skrive nye anmeldelser uanset om sitet er åbent for slutbrugerne eller ej. 
Man får fejlen, når man trykker OK for at gemme en ny eller redigeret anmeldelse.

**Comment by kkdbc** [comment]
@AndersFriisBrodsgaard tester

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev
