### ISSUE TITLE
Cookie-advarslen fylder mere end skærmen på HTC

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#14]
(Bugz 20238 - mdy)
Cookieadvarsel HTC

Cookie-advarslen kan ikke ses på HTC Desire uden at man skal scrolle. Ville
være fint hvis den tilpasser sig skærmen. Se vedlagte

![screenshot_2016-04-18-11-53-14](https://cloud.githubusercontent.com/assets/18323273/14631547/38e0003a-0614-11e6-8677-084dd35777e3.png)

**Comment by fvsdbc** [comment]
Er ikke sikker på at det løser problemet. Findes også på galaxy S5 browser med det passende navn internet, men ikke i chrome på samme.
