### ISSUE TITLE
Meddelelse om at der er lukket for at skrive anmeldelser vises forkert

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#140]
Den røde baggrundsfarve dækker ikke hele teksten + meddelelsen skal stå lige under tekstfeltet.
Det skal alt i alt fungere ligesom ved opret indlæg på gruppesiden.

**Comment by kkdbc** [comment]
@AndersFriisBrodsgaard tester

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
