### ISSUE TITLE
Meddelelse om reservationer klar til afhentning vises ikke under "Beskeder".

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#141]
Jeg har testet i Chrome og Safari med egne lånerdata og med data fra vores Roskilder-bruger og Albertlund/Integra.

**Comment by fvsdbc** [comment]
For mig funker det
![klar_til_afhentning](https://cloud.githubusercontent.com/assets/3070049/17204479/0c3ea23a-54a6-11e6-8a6c-7bc128fcdbe4.png)

**Comment by AndersFriisBrodsgaard** [comment]
Virker også for mig nu.
Lukker.
