### ISSUE TITLE
Moderatorer kan ikke logge på

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#144]
To moderatorer fra Roskilde bib kan ikke logge på. Den ene får denne besked:

"There have been more than 5 failed login attempts for this account. It is temporarily blocked. Try again later or request a new password. "
Hun har trykket på nyt password, men får ingen mail.

Hun hedder Stine Hansen. Er der nogen der kan hjælpe?

**Comment by hyatt03** [comment]
Er det i admin?

**Comment by Mariannedybkjaer** [comment]
Ja – admin.biblo.dk. Undskyld det ikke var klart

Fra: Jonas Peter Hyatt [mailto:notifications@github.com]
Sendt: 8. juli 2016 12:53
Til: DBCDK/biblo <biblo@noreply.github.com>
Cc: Marianne Dybkjær <mdy@dbc.dk>; Author <author@noreply.github.com>
Emne: Re: [DBCDK/biblo] Moderatorer kan ikke logge på (#144)


Er det i admin?

**Comment by hyatt03** [comment]
Jeg har ændret hendes kode og sendt den til dig over slack @Mariannedybkjaer
