### ISSUE TITLE
Upload af billeder er meget ustabil

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#145]
Jeg har fået denne henvendelse i kundeservice:
Upload at billeder til indlæg i grupper er fortsat meget meget ustabil, og har været det i en uges tid. Jeg har ikke hørt noget, og fejlmelder det derfor igen.

Når jeg forsøger at lægge et billede op, hænger den længe, hvorefter siden i stedet viser mig moderatorernes kommunikation (se vedlagte
![fejl_billeder-biblo](https://cloud.githubusercontent.com/assets/1375270/16726379/2e910b72-475c-11e6-92ab-1fa20e0c15d5.png)
Vil nogen se på den?

vh
Marianne

**Comment by Mariannedybkjaer** [comment]
Endnu en henvendelse om billedupload der fejler fra Michele på Aalborg bibliotek

**Comment by AndersFriisBrodsgaard** [comment]
Problemet er ikke aktuelt længere
