### ISSUE TITLE
Besked om at indlægget ikke må være tomt, skal forsvinde ved tryk på OK-knap

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#147]
Hvis man prøver at skrive et indlæg i en gruppe uden at have tilføjet noget tekstindhold, får man fejlbesked om, at indlægget ikke må være tomt. Hvis man derefter skriver noget tekst og trykker OK, oprettes indlægget som det skal, men fejlbeskeden forsvinder ikke. 

https://www.dropbox.com/s/wnyzgb14kvwg10s/Screenshot%202016-07-12%2015.07.21.png?dl=0

**Comment by KiraH** [comment]
testet OK
