### ISSUE TITLE
optælling af følgere på gruppesiden er +1

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#15]
I gruppeoversigten vises antal følgere under hver gruppe.
antal profilbilleder svarer til det der er optalt på gruppeoversigten, mens optællingen på gruppesiden altid er +1

**Comment by AndersFriisBrodsgaard** [comment]
Prioriteret på tavlen

**Comment by hyatt03** [comment]
løst af @matiaslaurarasmussen

**Comment by AndersFriisBrodsgaard** [comment]
Tjekket OK på biblo.demo
