### ISSUE TITLE
Kommentarer til indlæg dubleres

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#150]
I Faxe oplever man, at kommentarer til indlæg vises under beskeder flere gange. Altså: En bruger opretter et indlæg i en gruppe. En anden bruger kommenterer indlægget. I den første brugers Beskeder-liste kommer kommentaren til at stå flere gange.
Eksemplerne er fra grupperne Minecraft i Palleland og Tegne elskere. Se vedlagte.
![dublet1](https://cloud.githubusercontent.com/assets/1375270/16908137/b38da638-4cc9-11e6-8846-3abd0dc9215a.png)
![dublet2](https://cloud.githubusercontent.com/assets/1375270/16908149/b88fe470-4cc9-11e6-8440-ddd4da6ce385.png)

**Comment by hrmoller** [comment]
Indenfor samme sekund oprettes der to eller flere beskeder i dynamo der henviser til den samme kommentar hvorfor den samme besked optræder flere gange i brugerens strøm.
Næste udrulning fikser muligvis problemet.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
