### ISSUE TITLE
Voksenfilm på Biblo?

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#155]
I en henvendelse spørger Dorthe fra Roskilde på vegne af en bibliotekar:
"Jeg ville se hvad biblo.dk  kan tilbyde af film. Derfor klikkede jeg bare på ”film” ikonet efter jeg havde slettet min foregående søgning i søgefeltet. Det giver dette resultat som ligner en fuld bibliotek.dk søgning https://biblo.dk/find?q=&emneord=&materialer=movie  Jeg kan da i hvert fald se at biblo.dk har film om prostatakræft mm. Det ligner ikke en enlig smutter."

Er der ikke kriterier for, hvilke film der vises på Biblo?

**Comment by hyatt03** [comment]
Vi viser alt hvad der kan findes i biblo brønden, hvis der er kommet noget med som ikke skal, må vi lige snakke med DATA.

**Comment by Mariannedybkjaer** [comment]
Ok. Jeg har spurgt DATA. Lukker denne.
