### ISSUE TITLE
Besked når man har materiale der skal afleveres

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/biblo#156]
Har 3 bøger der skal afleveres i morgen, men beskedden på skærmen er at de skal afleveres senest om 10 timer. 
Dvs. tiden for aflevering er nok 1 minut over midnat.
Der burde nok stå i morgen.

**Comment by hyatt03** [comment]
Dubblet, se issue #128

**Comment by fvsdbc** [comment]
Fixet i #128
