### ISSUE TITLE
Like er muligt for anonym-bruger

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#16]
(afb: bugz 20180)
Som ikke-indlogget bruger kan jeg like andres indlæg. Jeg skal være logget ind
for at kunne like.

**Comment by kkdbc** [comment]
som jeg ser det, kan man ikke like når man ikke er logget ind. "hjertet" ses,
men det kan ikke aktiveres. Er det der efterspørges i virkeligheden at der
kommer en meddelelse som ved følg og indlæg, hvor der står man skal være logget
ind?
/Karin

**Comment by kkdbc** [comment]
vil du tage stilling til denne?

**Comment by AndersFriisBrodsgaard** [comment]
Den er fikset, ser det ud til. Tror at Matias har klaret den.
Vi blev enige om, at lade være med at give feedback på like-knappen i første omgang, indtil der er implementeret en generel måde at give feedback på.
