### ISSUE TITLE
Linieskift i beskrivelse af gruppe fjernes ved gem

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#17]
(afb: bugz 20173 Når man redigerer en gruppe og laver linieskift i beskrivelsen, vises disse
linieskift ikke i beskrivelsen på gruppesiden.

**Comment by kkdbc** [comment]
minor

**Comment by AndersFriisBrodsgaard** [comment]
Er oprettet som user story i ScrumDo
