### ISSUE TITLE
visning af bibliotek under profile bruger branchShortName mens suggesteren bruger branchName

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/biblo#176]
Ensretning så det som vælges også efterfølgende er det som vises

**Comment by KiraH** [comment]
@fvsdbc prøv med stenløse bibliotek

**Comment by fvsdbc** [comment]
openPlatforms suggester, leverer branchShortName for Stenløse, men branchName for hovedbiblioteket i Kbh.

Så det efterfølgende opslag i openAgency, der henter navnet efter profilen er gemt, har ikke mulighed for at vælge identisk med suggesteren.

Spørgsmålet må så være, hvorledes suggesteren er nået frem til to forskellige metoder til at faslæge et biblioteks navn

**Comment by fvsdbc** [comment]
... og suggesteren kører på et (gammelt) snapshot af indholdet i VIP. Der er derfor en opgave i at få dette opdateret med en eller anden frekvens

**Comment by kkdbc** [comment]
@AndersFriisBrodsgaard - der skal besluttes hvad der er mest hensigtsmæssigt og evt. udvidelse af SP

**Comment by AndersFriisBrodsgaard** [comment]
Afventer fix fra XP på opdatering af suggestservicen.
