### ISSUE TITLE
 iOS problemer med knapper på rediger indlæg

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#18]
(afb: bugz 20169) Rediger-knappen (blyanten) på et indlæg er svær at aktivere med fingeren, især
efter at have været aktiveret en gang før.

Det ser ud til, at der er de kendte problemer med knapper i iOS for "Slet",
"Fortryd" og "OK" - knapperne, som kommer frem ved rediger indlæg. De reagerer
ikke ved første tryk og kræver at man rammer bestemte dele af knapperne for at
de virker.

**Comment by EjnarSlot** [comment]
testet ok på ipad

**Comment by AndersFriisBrodsgaard** [comment]
Jeg får stadig fejlen på knapperne til Upload video eller billede og Fortryd (i forbindelse med at rette et indlæg eller en kommentar) på iOS, iPhone: De reagerer ikke på mine klik. 
Har testet på biblo.dk efter at vi har rullet ud i dag.

**Comment by AndersFriisBrodsgaard** [comment]
Prioriteret på tavlen

**Comment by jacobandresen** [comment]
Jeg tænker at redirect'et undervejs kan have indlydelse på knapperne på ios.  Jeg har en refactor undevejs. stay tuned.

**Comment by jacobandresen** [comment]
reafactoren løste ikke problemet. Jeg prøver nogle rettelser ifht user-scalable=no  ifht ios.

**Comment by jacobandresen** [comment]
user-scalable=no fix her : https://github.com/DBCDK/biblo/commit/b9294d925f9cc8e386f394a0571212b072370be0

**Comment by jacobandresen** [comment]
Jeg tænker at @hrmoller  måske har løst problemet med det her commit ? https://github.com/DBCDK/biblo/commit/483c572474dc57c18fdd181300f89da1951b40fa

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev
