### ISSUE TITLE
der vises kun 5 biblioteker i liste

### ISSUE THREAD

**Issue by kkdbc** [DBCDK/biblo#19]
(kh bugz 20100) 
Når man skal vælge bibliotek vises der kun 5 biblioteker i den verificerede
liste.

Man kan ikke bladre ned gennem listen, den ændrer sig dog hvis man skriver mere
ind.

Det er ikke rigtig defineret hvordan det skal laves, men skal nok lige vendes,
nu skriver jeg den ind her.

**Comment by AndersFriisBrodsgaard** [comment]
Der er kommet en henvendelse fra Københavns Biblioteker, som har svært ved at få Københavns Hovedbibliotek frem i forslagslisten. 
Jeg finder ud af, hvordan den skal løses.

**Comment by AndersFriisBrodsgaard** [comment]
Prioriteret på tavlen

**Comment by hyatt03** [comment]
@AndersFriisBrodsgaard Vi skal bruge nyt design til dette.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
