### ISSUE TITLE
Profilbilleder i gruppeoversigten mangler for alle andre end ejeren

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#190]
Iøjeblikket mangler profilbillederne for alle andre end ejeren her :https://biblo.dk/grupper/4

![skaermbillede 2016-08-01 kl 09 01 27](https://cloud.githubusercontent.com/assets/15238/17285979/a3ab805c-57c6-11e6-9207-11007d4f50f2.png)

**Comment by hyatt03** [comment]
fixed #96de121

**Comment by jacobandresen** [comment]
testet ok
