### ISSUE TITLE
beskeder om bøger til afhentning mangler

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#199]
Jeg har reserveret 4 bøger der er kommet hjem på biblioteket i går, men jeg har ikke fået nogle beskeder i biblo. Hverken på dev eller prod.

**Comment by fvsdbc** [comment]
prøv igen på dev - det virkede ej heller hos mig p.gr.a. en fejl vedr logning. Men efter rettelsen er de dukket op.

**Comment by KiraH** [comment]
Det virker nu.
