### ISSUE TITLE
man er stadig logget ind selv om browseren har været lukket

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#212]
Tidligere blev man logget ud, hvis browseren blev lukket. Det gør man ikke mere. Hvis jeg logger på, lukker alle faner og browser, er jeg stadig logget ind hvis jeg åbner browseren igen.

Hvis jeg logger ud og derefter lukker browseren virker det OK.

**Comment by AndersFriisBrodsgaard** [comment]
Tjekket OK.
