### ISSUE TITLE
Søgefeltet opfører sig ustabilt 

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#217]
Henvendelse fra Nilex "Søgefeltet - markør rykker automatisk tilbage
Når man skal søge på en bog i søgefeltet, rykker den nogen gange automatisk tilbage efter man har trykket på mellemrumstasten. Jeg havde en bruger som sagde hun havde oplevet samme problem"

Både NLA og jeg har også oplevet at markøren rykker 1 eller 2 bogstaver retur under indtastning i søgefeltet. I starten troede jeg det var mit tastatur, den var gal, men det sker kun på biblo.dk - oplevet i IE11.

**Comment by AndersFriisBrodsgaard** [comment]
Steps to reproduce ønskes.

**Comment by lho** [comment]
Åbn biblo.dk i IE11 -> skriv hurtigt i søgefeltet: gamle gule. Gamle bliver til game osv. Kom evt over og se :)

**Comment by fvsdbc** [comment]
Har prøvet ved at fake forsinkelse lidt forskellige steder i koden, men jeg kan ikke reproducere fejlen i chrome eller FF. Kan heller ikke (med min viden) finde noget i koden, som kan forklare det.

Det ligner at det er suggest som får noget til at opføre sig uhensigtmæssigt i IE11 - det er kun i søgefeltet det sker.
