### ISSUE TITLE
Rediger profil fejler

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#22]
Iøjeblikket fører et klik på rediger profil til en fejlside. Jeg logger ind som brugeren "zoner3d" når jeg oplever fejlen.

**Comment by AndersFriisBrodsgaard** [comment]
Har fået henvendelse fra en slutbruger, der får samme fejl på biblo.dk
Og Laura får den samme fejl også.

**Comment by hyatt03** [comment]
Problemet er at OpenAgency giver et andet svar hvis biblioteket ikke har angivet oversættelser af branchName, dette skal vi så bare håndtere...

**Comment by AndersFriisBrodsgaard** [comment]
Så det er når profilsiden skal håndtere visning af det valgte bibliotek, at problemet opstår?

**Comment by hyatt03** [comment]
Det er backenden der skal håndtere det

**Comment by AndersFriisBrodsgaard** [comment]
OK

**Comment by jacobandresen** [comment]
openagency smider en enkelt værdi istedet for et array , når der kun er en værdi.  Med den nuværende implementation vil redigering af profiler med "Tårnby Kommunebiblioteker" fejle . Jeg indsætter et fix der henter branchShortName ud fra openagency  både i det tilfælde at den returnerer værdien som en liste og som en en variabel. På sigt kan dette ensrettes via serviceprovideren.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev

**Comment by jacobandresen** [comment]
ups. forrige commit-besked var til #18.
