### ISSUE TITLE
Fejl ved link til lån af ebog

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#224]
Når jeg trykker på bestil for et værk, der både findes som bog og ebog, og derefter vælger ebog som det ønskede materiale, får jeg i modalvinduet (hvor man vælger materialetype) beskeden: " Du skal vælge hvad du vil låne, før du trykker OK" selv om jeg har valgt ebog.
Fx. https://biblo.dk/materiale/870970-basis:01167839
Fejlen er set i Safari og Chrome, OSX. 
Fejlen opstår ikke for alle værker, der indeholder ebøger, fx. ikke https://biblo.dk/materiale/870970-basis:05723884
Ved markering af egob som det ønskede materiale, bør knapteksten skifte til "Hent online" i stedet for OK, men det sker ikke for den ovennævnte post.

![screenshot 2016-08-09 13 46 06](https://cloud.githubusercontent.com/assets/18284484/17515471/dc8ff7d6-5e38-11e6-9a2b-b5af54f2f2ee.png)

**Comment by fvsdbc** [comment]
besked kan nu sendes selvom fejlbesked vises

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK mht. mulighed for at trykke OK.
Datagrundlaget var forkert, derfor figurerede ebogen forkert.
