### ISSUE TITLE
Man kan ikke slette beskeder i Safari OSX og iOS

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#226]
Jeg kan slette mine beskeder under “Beskeder"-fanebladet i Chrome, men ikke i Safari OSX eller Safari iOS. Der kommer ikke nogen reaktion på mine klik.

**Comment by kkdbc** [comment]
@AndersFriisBrodsgaard tester

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev
