### ISSUE TITLE
Jeg får ikke notifikation ved kommentarer til indlæg, jeg har skrevet

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#227]
Når nogen kommenterer et indlæg, jeg har skrevet, får jeg ikke en notifikation, og der optræder heller ikke nogen beskeder under "Beskeder"-fanebladet. 
Testet på biblo.dk

**Comment by jacobandresen** [comment]
@AndersFriisBrodsgaard  Gider du prøve at teste på biblo-dev for at se om problemet er der ? Jeg tror at der har været knas ifm omrykning af smaug.

**Comment by AndersFriisBrodsgaard** [comment]
Har testet OK på biblo-dev.
Dog får jeg ikke push-notifikationer, dvs. jeg skal reloade for at tallet ved mit profilbillede opdateres.
