### ISSUE TITLE
Indlæg slettes ikke med det samme ved sletning af indlæg

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#229]
Når jeg sletter et indlæg erstattes mit profilbillede og profilnavn med standardbillede og "Anonym" og indlæggets indhold bliver til teksten "undefined".
Ved efterfølgende reload af siden forsvinder indlægget som det skal. 
Testet på biblo.dk Safari OSX
https://biblo.dk/grupper/86

![screenshot 2016-08-09 16 47 45](https://cloud.githubusercontent.com/assets/18284484/17520795/4e954990-5e51-11e6-8f48-951c542730a6.png)

**Comment by AndersFriisBrodsgaard** [comment]
Problemet er ikke konsistent og opstår altså ikke hver gang, jeg sletter et indlæg.

**Comment by kkdbc** [comment]
@afb tester

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev
