### ISSUE TITLE
Baggrund i svg-ikon for grupper på søgesiden skal være transparent

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#232]
Lige nu er den hvid.
![screenshot 2016-08-10 14 00 05](https://cloud.githubusercontent.com/assets/18284484/17552878/e5e96784-5f02-11e6-8803-ea8b1b1ecb61.png)

https://biblo.dk/find?q=sweet&grupper=0&emneord=&materialer=

**Comment by fvsdbc** [comment]
Mangler en svg fil group_no_border.svg - svarende til book_no_border.svg - der er kun en group.svg (som ikke er transparent.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
