### ISSUE TITLE
Laver vi bestillinger, hvor kun den valgte udgave kan bruges?

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#237]
Jeg lavede en fejlagtig bestilling til Roskilde Bibliotekerne og fik nedenstående svar, hvori der står: "Kun den valgte udgave kan bruges"

Til: 

Materialet du har bestilt er et netdokument, og kan ikke skaffes. Du kan slå materialet op på www.bibliotek.dk og se hvilke biblioteker der har adgang til netdokumentet, og benytte det hos dem.

Palles Gavebod bestilling til Roskilde Bibliotekerne (726500)
## Sendt den 10-08-2016. BestilID: 1023351787

Bestilt materiale:
Munk, Britta: Hotel Hanne : ungdomsroman - 2016
NETDOKUMENT 1. e-bogsudgave - Lindhardt og Ringhof, 2016 - (Hanne-bøgerne ; [2])
Idnr: 52178797
ISBN: 9788711499016

Ugekoder: DBF201608 BKM201608 DAT201611
Opstilling: sk
Interessedato: 08-11-2016
Kun den bestilte udgave kan bruges

**Comment by KiraH** [comment]
Ja, det er jeg ret sikker på vi gør. Jeg har oplevet at få fjernlånt ting jeg har bestilt fordi egedal ikke havde den udgave jeg havde søgt frem i biblo. Så jeg tænker også vi måske skal vende om det er det vi vil.

Fra: AndersFriisBrodsgaard [mailto:notifications@github.com]
Sendt: 11. august 2016 10:48
Til: DBCDK/biblo <biblo@noreply.github.com>
Emne: [DBCDK/biblo] Laver vi bestillinger, hvor kun den valgte udgave kan bruges? (#237)


Jeg lavede en fejlagtig bestilling til Roskilde Bibliotekerne og fik nedenstående svar, hvori der står: "Kun den valgte udgave kan bruges"

Til:

Materialet du har bestilt er et netdokument, og kan ikke skaffes. Du kan slå materialet op på www.bibliotek.dk<http://www.bibliotek.dk> og se hvilke biblioteker der har adgang til netdokumentet, og benytte det hos dem.

Palles Gavebod bestilling til Roskilde Bibliotekerne (726500)

Sendt den 10-08-2016. BestilID: 1023351787

Bestilt materiale:
Munk, Britta: Hotel Hanne : ungdomsroman - 2016
NETDOKUMENT 1. e-bogsudgave - Lindhardt og Ringhof, 2016 - (Hanne-bøgerne ; [2])
Idnr: 52178797
ISBN: 9788711499016

Ugekoder: DBF201608 BKM201608 DAT201611
Opstilling: sk
Interessedato: 08-11-2016
Kun den bestilte udgave kan bruges

**Comment by AndersFriisBrodsgaard** [comment]
Ved overgang til bestil via serviceprovider skal der tilføjes mulighed for at anføre exactEdition-parameteret i serviceprovideren. Der skal oprettes et separat issue på dette.

**Comment by AndersFriisBrodsgaard** [comment]
https://github.com/DBCDK/serviceprovider/issues/594

**Comment by AndersFriisBrodsgaard** [comment]
I forbindelse med vores implementation af bestillinger via ServiceProvider, skal vi tilføje dette parameter i bestillingerne fra Biblo. ExactEdition=false.

**Comment by vibjerg** [comment]
ServiceProvideren har implementeret exactEdition=false, og denne bug er løst med udrulningen af SD-651

**Comment by AndersFriisBrodsgaard** [comment]
I BOB-basen har bestillinger fra Biblo anført, at kun den valgte udgave kan bruges. Der sker altså et eller andet i forbindelsen mellem Biblo og OpenPlatform eller OpenPlatform og OpenOrder.
- Sender OpenPlatform den rigtige information videre til OpenOrder?
- Kan der være nogle faste indstillinger i OpenOrder, der altid sætter bestillinger fra PG/Biblo til exactEdition=true?

**Comment by fvsdbc** [comment]
Har sendt bestillinger direkte gennem openOrder, og lige gyldigt hvad exactEdition sættes til, så optræder alle i bob som kun den valgte udgave kan bruges.

**Comment by fvsdbc** [comment]
ExactEdition sættes af bestil-systemet. Bestilles kun en pid, videreføres det som at man kun ønsker den valgte udgave, er der mere end en pid i bestillingen, sættes at man gerne vil have andre udgaver.
Så ansvaret for at finde de alternativer som en bestilling kan tilfredsstilles med, er overladt til klienten, fx. ved at sende samtlige pid'er som et værk består af (begrænset til samme materialetype - det som i biblbiotek.dk er kaldt underværker)
