### ISSUE TITLE
Bruger, der gerne vil slettes

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#241]
En bruger vil gerne have slettet sin profil på Biblo:
Dani Cool: https://biblo.dk/profil/48206
Brugeren har ikke nogen (synlige) anmeldelser, indlæg eller kommentarer.

**Comment by hrmoller** [comment]
Brugeren er blevet slettet. Intet andet indhold lavet af brugeren blev fundet.
