### ISSUE TITLE
Profilbillede på profilside er trykket sammen

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#258]
Se fx https://biblo.demo.dbc.dk/profil/808
Billedet skal beskæres og ikke presses sammen for at passe ind i cirklen.
Desuden er brugernavn og brugerens beskrivelse rykket for langt ned.

**Comment by AndersFriisBrodsgaard** [comment]
Det ser ud til, at der i stedet er kommet et andet problem med profilbilledet.

<img width="1051" alt="screenshot 2016-09-26 23 09 37" src="https://cloud.githubusercontent.com/assets/18284484/18851923/70d3a6ce-843e-11e6-960f-386a4f9f3af7.png">

**Comment by fvsdbc** [comment]
for nogle er square billedet ikke square - har tilføjes drop/resize så de også ser ok ud.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
