### ISSUE TITLE
Jeg skal ikke have notifikation om indlæg eller kommentarer, jeg selv har oprettet

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#259]
Jeg skal ikke have notifikation eller besked om mine egne kommentarer til mine egne indlæg.
Jeg skal ikke have notifikation eller besked om mine egne kommentarer til indlæg, jeg i forvejen har kommenteret.
Når jeg opretter et indlæg i en gruppe, jeg følger, tæller det med i antal nye indlæg i gruppen på Grupper-knappen på min profilside. Det skal det ikke.

**Comment by fvsdbc** [comment]
Håber det hele er fixet
