### ISSUE TITLE
LatestGroupPostsWidget viser ikke indlæg per default / viser mange indlæg ved tryk på "Vis flere"

### ISSUE THREAD

**Issue by kasperg** [DBCDK/biblo#262]
På https://biblo.demo.dbc.dk/section-page viser widgeten "Endnu flere indlæg" inden indlæg, når siden loades. Ved tryk på "Vis flere" vises 20 indlæg (NB: Samme som postsToLoad værdien i definitionen).

Jeg havde forventet at widgetten havde vist 3 indlæs, når siden loades, og yderligere 3 indlæg hver gang der trykkes på "Vis flere".

![section page - biblo dk 2016-08-22 16-41-04](https://cloud.githubusercontent.com/assets/73966/17858753/40991886-6887-11e6-97b6-99c4055253c5.png)

![section page - biblo dk 2016-08-22 16-42-17](https://cloud.githubusercontent.com/assets/73966/17858780/660b31d0-6887-11e6-93d0-f341a8e7dbd6.png)

**Comment by kasperg** [comment]
Ping @AndersFriisBrodsgaard.

**Comment by fvsdbc** [comment]
Cool fejl. Man får indlæg fra sidste klik, dvs. resultatet er på en måde bare et klik bag ud.
