### ISSUE TITLE
Får "Dit bibliotek modtager ikke bestillinger" når jeg forsøger at bestille materialer

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#275]
Forsøger at bestille på Herlev og Ballerup, men får samme fejl begge steder.
https://biblo.dk/materiale/870970-basis:51418816#!

![screenshot 2016-08-24 15 13 37](https://cloud.githubusercontent.com/assets/18284484/17931828/919699c0-6a0d-11e6-9720-f6ae428d0cdb.png)

**Comment by vibjerg** [comment]
Er løst med https://github.com/DBCDK/biblo/pull/248

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på biblo-dev
