### ISSUE TITLE
Lånerstatus opdateres ikke

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#281]
Materiale bliver vist med forkert status (overskredet afleveringsdato) selvom materialet er fornyet hos bibliotek.
(nilex 44328 + MDY har eksempel på dette under sine beskeder)

**Comment by KiraH** [comment]
@lho Det er fordi det ikke er lånerstatus men notifikationer. De opdateres ikke, men bliver ved at stå som da de kom ind.

**Comment by AndersFriisBrodsgaard** [comment]
Det svarer til en email-indbakke. Man kan slette notifikationerne på det lille kryds. 
Vi har dog en userstory, som automatisk vil fjerne de beskeder fra biblioteket, som ikke længere er aktuelle.
