### ISSUE TITLE
Skalering af billeder i Mine grupper under Profil fejler på biblo-dev.demo.dbc.dk

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#29]
Billederne for grupper i modalvinduet under "Profil" -> "Mine grupper" er for store. De har har den rigtige størrelse i drift.

**Comment by AndersFriisBrodsgaard** [comment]
Er det på demo.dbc? Her ligger billederne i venstre side. De skal fordeles i bredden som på drift.
![skaermbillede 2016-05-26 kl 22 21 48](https://cloud.githubusercontent.com/assets/18284484/15588856/431dcbec-2390-11e6-8417-7eedfb341e62.png)

**Comment by hyatt03** [comment]
Nej, biblo-dev.demo.dbc.dk

**Comment by KiraH** [comment]
testet OK
