### ISSUE TITLE
Bestil viser kun e-materialer, selv om posten findes med andre materialetyper

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#293]
Når jeg er logget ind uden at have udfyldt biblioteksinfo, får jeg kun mulighed for at bestille e-materialer, da disse er tilgængelige uden at være logget ind / uden biblioteksinfo. 
Jeg skal have besked om at udfylde biblioteksinfo for at låne de andre materialetyper.

**Comment by fvsdbc** [comment]
Er sandsynligvis udbedret ved løsning af issue 303
