### ISSUE TITLE
Billeder på forsiden (fx profilbilleder i widgets) er alt for tunge

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#306]
Vi skal have gennemgået hvor vi har problemer med for tunge billeder på forsiden.
Henter vi billeder i de rigtige størrelser fra Amazon/forsideservice?
For vi de rigtige størrelser tilbage fra Amazon?
Opret evt. en selenium test, der tjekker den samlede størrelse for forsiden.

**Comment by AndersFriisBrodsgaard** [comment]
Problematikken er den samme med billeder uploadet i en gruppe
https://biblo.dk/grupper/4
Billedet skal vises i en skaleret version, når det ligger i indlægget, men skal vises i fuld størrelse, når brugeren klikker på det (som det sker nu).

**Comment by AndersFriisBrodsgaard** [comment]
Det ser ud til, at vi spørger Amazon efter billederne i de rigtige størrelser - både i forbindelse med profilbilleder på forsiden og med billeder i indlæg - men at det er den originale størrelse, der returneres fra Amazon.

**Comment by hyatt03** [comment]
Det ser ud til at biblocsbe-p01 ikke har haft redis sat korrekt op, dette kan være en stor del af problemet.

**Comment by hyatt03** [comment]
Der kørte en rouge cs på biblocs-p01, som var meget forældet og havde forkerte koder. Den skabte ballede. Måske vi skal se om der er nogle gamle system.d scripts der har sparket den i live.

**Comment by hyatt03** [comment]
Jeg har sat de billeder som ikke var skaleret i kø, så det bør snart være godt igen :)

**Comment by KiraH** [comment]
@hyatt03 Der lå et gammelt systemd script, der ikke var blevet disablet. Det er disablet nu. Så hvis det er det der har lavet ballade, så sker det ikke igen.
