### ISSUE TITLE
Lån knap skal have en anden grøn farve og VERSALER

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#31]
Der skal stå LÅN på knappen og knapfarven skal være: 1bca1b, rollover: 73f175

**Comment by hrmoller** [comment]
Fikset med 006e5a8eeb485efeefaf433e4482ee87a06852ea

**Comment by KiraH** [comment]
Jeg ved ikke om farven er korrekt, men "lån" står ikke med versaler.

**Comment by AndersFriisBrodsgaard** [comment]
Kan ikke se hvor det er "fixed"

**Comment by hrmoller** [comment]
Nu med Cucumber-test: https://github.com/DBCDK/biblo/commit/ae2981781e4f1b409fa6a664165365f584e21889#diff-b34301cdc5be35714ed8f6eb6ff39aa7R7

[Farve screenshot](https://www.dropbox.com/s/nv2waz0zortegrv/Screenshot%202016-06-30%2011.44.53.png?dl=0)

**Comment by KiraH** [comment]
testet OK
