### ISSUE TITLE
Mangler overskrift på forsiden

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#317]
Jeg kunne godt tænke mig en overskrift på forsiden over indlæggene med EreolenGo, Buster og Vild med fillm. Se vedlagte. Det ser ud som om det hænger sammen med Seneste anmeldelser
![biblo_overskrift](https://cloud.githubusercontent.com/assets/1375270/18311742/4c9a3aa8-7506-11e6-9bcc-a7b9ae3310ae.png)

**Comment by AndersFriisBrodsgaard** [comment]
Spotsene kommer på sigt til at ligge i en widget, hvor der bliver mulighed for at angive fx baggrundsfarve og evt. overskrift. Pt bliver disse spots hentet fra en json fil på amazon. Vi regner med at køre den nye version i drift i løbet af denne uge.
