### ISSUE TITLE
"Vælg bibliotek"-dropdown på opret profil / rediger profil skal kunne benyttes med piletasterne.

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#32]
Man skal kunne vælge et element i dropdown'en ved at benytte op- og nedpiletasterne.

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Måske du skal lave en US på det.

**Comment by AndersFriisBrodsgaard** [comment]
Done.
ScrumDo #579
