### ISSUE TITLE
Billeder fra admin skal hentes med https

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#320]
Fx kampagneikoner og billeder i artikelsider. Pt. hentes de via http.

**Comment by hyatt03** [comment]
Admin issue

**Comment by AndersFriisBrodsgaard** [comment]
@vibjerg Er denne fikset? Hvis ikke, giver det så mening, at kigge på den i forbindelse med det andet arbejde på admin?

**Comment by vibjerg** [comment]
Bliver løst med https://github.com/DBCDK/biblo-admin/issues/190
