### ISSUE TITLE
Haster lidt - gruppe kan ikke søges frem

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#327]
Gruppen Harry Potter Festival findes ikke i søgeresultatet, hvis man søger på fx festival eller harry. Den er oprettet i sidste uge og findes under nyeste grupper. Så den er der, men altså ikke i en søgning. Den er oprettet af Dynke fra Odense bibliotek.

**Comment by hyatt03** [comment]
Bliver fikset i biblocs

**Comment by Mariannedybkjaer** [comment]
Ak - gruppen, det drejede sig om hedder Harry Potter festival **Odense**, og nu er den helt væk. Findes ikke længere under Nye grupper. Vil I se på den nok en gang?

**Comment by hyatt03** [comment]
Er det ikke denne? ![screen shot 2016-09-20 at 09 15 25](https://cloud.githubusercontent.com/assets/2140680/18660841/ea80b240-7f12-11e6-8ad5-4a066fd3fb98.png)
