### ISSUE TITLE
"Følger"-knappen viser ikke at jeg følger en gruppe

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#33]
Når jeg går ind på en gruppeside for en gruppe, som jeg følger, står der "Følg gruppen" på knappen. Det skal være "Følger". 
https://biblo.demo.dbc.dk/grupper/1

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Gider du lige teste igen?

**Comment by hrmoller** [comment]
Kan ikke reproducere lokalt med CS på uxscrum
På biblo.dk gælder det grupperne med id ≈ 1 - 5 på biblo.demo er gælder det tilsyneladende også nogle af grupperne med lave id'er.

**Comment by AndersFriisBrodsgaard** [comment]
@hrmoller som jeg forstår det, skyldes det en tidligere fejl som ikke længere findes. Men vi bliver nok nødt til at fikse fejlen alligevel, da den berører de pt. mest anvendte grupper på Biblo.

**Comment by hrmoller** [comment]
@hyatt03 gider du kigge med her?

**Comment by hyatt03** [comment]
@hrmoller Jeg ser lige på det :)

**Comment by hrmoller** [comment]
Optur!

--
Martin Møller Jensen
Software Udvikler | Software Developer
DBC A/S | Tempovej 7-11, 2750 Ballerup
Tlf.: 51 82 62 08<tel://51%2082%2062%2008>
Lok.: 618
mmj@dbc.dk<mailto:mmj@dbc.dk>


On 31 May 2016 at 09:17:38, Jonas Peter Hyatt (notifications@github.com<mailto:notifications@github.com>) wrote:

@hrmoller<https://github.com/hrmoller> Jeg ser lige på det :)

**Comment by hyatt03** [comment]
Problemet ligger i transformen, den definerer et limit på antal medlemmer den henter ud. 

Hvis en gruppe har over det standard antal medlemmer, og en ny person bliver tilføjet, kan det filter der tjekker for om en person følger gruppen ikke se den nye person.

**Comment by hrmoller** [comment]
Fedt @hyatt03 så har det intet at gøre med hvornår gruppen er lavet men antallet af følgere - det er godt!

**Comment by KiraH** [comment]
testet OK
