### ISSUE TITLE
Man kan oprette to anmeldelser af samme værk

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#333]
Det er lykkedes at oprette to anmeldelser af samme værk:
https://biblo.demo.dbc.dk/profil/808#ANMELDELSER
https://biblo.demo.dbc.dk/materiale/870970-basis:26521602
Måske ved at trykke to gange på "OK"-knappen hurtigt efter hinanden.
Det skal ikke være muligt.

**Comment by hrmoller** [comment]
Submit knappen bliver gjort inaktiv med det samme efter der er trykket på den.
