### ISSUE TITLE
Man kan ikke uploade filer af typen .mp4 til et indlæg/kommentar i en gruppe

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#34]
Testet på https://biblo.demo.dbc.dk/grupper/1
Bør man ikke kunne det?

**Comment by AndersFriisBrodsgaard** [comment]
OSX El Capitan, Safari 9.1

**Comment by jacobandresen** [comment]
Jeg prøver at indsætte video/mp4 ovenpå det eksisterende filter. Til ære for Safari. (Det ser ud til at virke lokalt).

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
