### ISSUE TITLE
Colored header laver ekstra overskrift

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#346]
Colored header på en sektionsside: Teksten i feltet ”Title” står i frontend både oven over headeren og inde i headeren. Jeg formoder at designet til netop denne header er sat op til at titlen kun skal stå inde i headeren. Overskriften oven over er til de widgets, der har automatisk indhold.

**Comment by AndersFriisBrodsgaard** [comment]
Tjekket OK.
