### ISSUE TITLE
To "Latest post lists" oven over hinanden: kun den øverste vises i frontend

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#348]
Når man sætter to af disse widgets op under hinanden er det kun den øverste der viser indholdet i frontend.

**Comment by fvsdbc** [comment]
Vil de widgets der fodres asynkront ikke altid ødelægge det for det ene at to "identiske" widgets?

**Comment by hyatt03** [comment]
Jeg kan ikke genskabe denne fejl, kan du sende et eksempel?

**Comment by AndersFriisBrodsgaard** [comment]
Eksempel på fejlen i produktion: https://biblo.dk/kampagner-paa-biblo
De to widgets SENESTE INDLÆG I SPØRG BIBLO og SENESTE INDLÆG I MINECRAFT I PALLELAND-GRUPPEN. Den første widget fungerer som den skal, mens den anden ikke viser noget indhold. 

Imidlertid er der ikke de samme problemer på demo og dev, så vi venter lige med at fikse noget i produktion, hvis det virker efter næste udrulning.
