### ISSUE TITLE
En ændring i en Latest post list fjerner gruppen

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#350]
Hver gang man ændrer noget i latest post listen fjerner den gruppen. Uanset hvad man ændrer. Man skal altid ind og sætte en gruppe på igen.

**Comment by AndersFriisBrodsgaard** [comment]
Flyttet til biblo-admin issues:
https://github.com/DBCDK/biblo-admin/issues/173
Lukker denne issue
