### ISSUE TITLE
Nogle videoer vises ikke i Embedded video

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#351]
Indhold fra dette link: https://www.youtube.com/watch?v=XRjHp3oJV1U&list=PLMNNvyo3OVwCn5HfCrQvcK9oC1DuO66it vises ikke i frontend. Andre kortere links vises.

**Comment by hrmoller** [comment]
@Klausstovring har du et link til en side hvor linket er indsat?

**Comment by AndersFriisBrodsgaard** [comment]
Ser ikke ud til at være et problem længere, lukker
