### ISSUE TITLE
Sektionssiden viser intet indhold

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#354]
Har lige lavet sektionssiden https://biblo.dk/kampagner-pa-biblo
Der ligger en header og et content grid med 5 content grid items på siden. Det bliver ikke vist i frontend. Hverken i Chrome eller Firefox

**Comment by AndersFriisBrodsgaard** [comment]
Det er fordi der er relative links i de oprettede content grid items. Hvis de bliver erstattet med absolutte links skulle det gerne virke.
Jeg har oprettet en bug på de relative links under bugs til admin-grænsefladen, så jeg lukker denne her bug. 
https://github.com/DBCDK/biblo-admin/issues/156
