### ISSUE TITLE
CMS: Structure/Menus/Main navigation, ændringer slår ikke igennem

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#358]
Jeg har ændret menulinket "Sommerbogen" til "Kampagner". Det er ikke slået igennem i frontend. Menulinket har i lang tid været disabled hvilket heller ikke er slået igennem. Når man trykker på menulinket i frontend (Sommerbogen) så viser den til en tom side.

**Comment by AndersFriisBrodsgaard** [comment]
Man skal tømme cachen i admin for at ændringer i menuen slår igennem. Da det er relativt sjældent, at menupunkterne skal ændres, har vi valgt at optimere cachingen med den bieffekt, at cachen skal tømmes ved opdatering i menuen.
Configuration -> Development -> Clear all caches
Jeg har lige gjort det på produktion, og der står nu kampagner i topmenuen.
