### ISSUE TITLE
Har ikke adgang til admin for demo uden VPN

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#36]
Der bør vel være adgang til admin for biblo.demo.dbc.dk uden VPN
Får en 403 på http://admin-stg.biblo.dk

**Comment by KiraH** [comment]
Ja, det burde du kunne, men det er ikke sikkert der er tænkt på det. Det følger jeg lide op på.

Fra: AndersFriisBrodsgaard [mailto:notifications@github.com]
Sendt: 26. maj 2016 22:58
Til: DBCDK/biblo
Emne: [DBCDK/biblo] Har ikke adgang til admin for demo uden VPN (#36)


Der bør vel være adgang til admin for biblo.demo.dbc.dk uden VPN
Får en 403 på http://admin-stg.biblo.dk
