### ISSUE TITLE
Forskellige muligheder ved bestil

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#38]
http://uxscrum-i02.dbc.dk:8080/materiale/870970-basis:27676413
Når jeg reloader siden og trykker "Lån" får jeg forskellige muligheder for at låne. Nogen gange kan jeg låne bøger og e-bog bind 1, andre gange kan jeg ikke. Jeg regner med, at det er checkorderpolicy der giver problemer?
Har også oplevet det på andre værksider. 
Jeg er tilknyttet Herlev Bibliotekerne.

**Comment by hrmoller** [comment]
Der bliver brugt en testversion af OpenOrder på uxscrum.

**Comment by hrmoller** [comment]
Har ændret til prod version af OpenOrder i smaug confi, det kræver dog ny udrulning af ServiceProvideren før det slår igennem. Indtil videre ville det være fint at få testet på et højere niveu end uxscrum.

**Comment by hyatt03** [comment]
Har indsat retry logic i clienten.

**Comment by KiraH** [comment]
testet OK
