### ISSUE TITLE
logning af meta.data.request knækker ELK

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo#380]
ELK'en har til tider svært ved at parse logs der kommer med `msg:Transform has been triggered` og det er tilsyneladende `meta.data.request` objektet den knækker på.

**Comment by hrmoller** [comment]
Der er lagt en logfil i ~mmj på devel8 (infratest.log)

**Comment by hrmoller** [comment]
Actual an issue on dbc-node-serviceprovider: https://github.com/DBCDK/dbc-node-serviceprovider/issues/12

**Comment by AndersFriisBrodsgaard** [comment]
Den refererede issue er fikset, så denne issue lukkes.
