### ISSUE TITLE
Man skal kunne få links til eReolen Go uden at være logget ind

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#382]
Når man på en værkside (for en post, der har eReolen materialer) klikker på "Lån på eReolen"-knappen skal der ikke laves et tjek af, om brugeren er logget ind og har udfyldt lånerinfo. Modalvinduet skal vises til alle brugere uanset om de er logget ind og give dem mulighed for at komme videre til eReolen Go.
Se fx https://biblo.dk/materiale/870970-basis:28949847

**Comment by hyatt03** [comment]
Fixed in #395

**Comment by AndersFriisBrodsgaard** [comment]
Tjekket OK på demo
