### ISSUE TITLE
Problemer med afbrudt forbindelse til server i Safari på OSX Sierra 

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#396]
De enkelte sider loader ikke færdig, så man får ofte helt blanke sider eller sider med kun få elementer. 

OSX 10.12
Safari 10.0

**Comment by vibjerg** [comment]
Problemet er ikke relateret til Socket forbindelser, men skyldes at forbindelsen til serveren bliver brudt forskellige steder. Ofte for man kun loadet en del af dom objektet. Ændrer titlen til at være mere retvisende

**Comment by vibjerg** [comment]
Problemet er kun i drift og kun når man loader sites via proxy. F.eks. findes problemet på biblo.demo.dbc.dk men ikke http://uxscrumdmz-i02:8006. 

Om problemet skyldes https eller proxy er endnu uklart. Måske @KiraH eller @csv kan se på problemet.

**Comment by vibjerg** [comment]
Der er ikke nogen problemer med at køre localhost via https. Det tyder på at problemet ligger i proxy opsætningen

**Comment by vibjerg** [comment]
Det ser umiddelbart ud til at problemet kun eksisterer når man er indenfor DBC's firewall. Problemet kan ikke genskabes på en ekstern forbindelse.

**Comment by AndersFriisBrodsgaard** [comment]
Fikset via Safari opdatering
