### ISSUE TITLE
iphone5s: Forkert ombrydning, når jeg scroller nedad i min profil (bugz 20155)

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#4]
Laura: Jeg er inde på min profil, scroller ned for at se ældre indlæg. efter lidt
scrolleri står redigeringsikonet (blyanten) oven i teksten om hvornår indlægget
er skrevet. og teksten ud for hjerteikonet ("kan godt lide dette") fordeler sig
lidt forkert.

**Comment by jacobandresen** [comment]
Det kan se ud som at der et issue med styling. Bredden er ud til at være afhængig af billedet.

**Comment by jacobandresen** [comment]
Jeg har fjernet gruppebilledet fra feedet

**Comment by kkdbc** [comment]
laura: Ups var lidt fordi med at lukke sagen. Hvis nogen liker et indlæg, så der fx
står (hjerte) 7 kan godt lide dette - så ryger det sidste ord (dette) ned under
svar knappen.

**Comment by jacobandresen** [comment]
Jeg har  ændret padding for like knappen på mindre skærmen .Det burde udbedre problemet.
