### ISSUE TITLE
"Vis flere"-knap ses selv om der ikke er flere resultater

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#40]
Der vises altid en "Vis flere"-knap, selv om man har hentet alle resultater i en søgning. Knappen skal kun være synlig, hvis der er flere resultater at hente.
https://biblo-dev.demo.dbc.dk/find?q=kendis&emneord=&materialer=

**Comment by KiraH** [comment]
samme som #37

**Comment by AndersFriisBrodsgaard** [comment]
Du skal ind på https://console.aws.amazon.com/

Har du password?

/A

—
Anders Friis Brødsgaard
afb@dbc.dk
61668424

**Comment by KiraH** [comment]
testet OK i søgning og kommentarer
