### ISSUE TITLE
Afstand mellem elementer på artikelside er for stor

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#411]
Tjek https://biblo.dk/er-du-vild-med-film
Afstanden mellem overskrifter og paragraffer er for stor - måske benyttes de margin-muligheder, der til widgets på sektionsside. 
![screenshot 2016-10-25 13 17 51](https://cloud.githubusercontent.com/assets/18284484/19684061/7aeabe08-9ab5-11e6-94f7-e725ccf2acd3.png)

**Comment by AndersFriisBrodsgaard** [comment]
Se fx. https://biblo.dk/er-du-vild-med-film

.generic-widget-container {
margin-bottom: 3em;
}
...skal for ContentPageTextWidget og ContentPageImageWidget være 0em

Evt. skal der også justeres på topmargin for samme elementer.

**Comment by AndersFriisBrodsgaard** [comment]
Cool
Har tjekket på Biblo demo, det er blevet bedre. Afstanden er stadig for stor efter min mening. Kan vi sætte noget andet styling på samme widgets:

.generic-widget-wrapper {
    padding: 1em;
}
-> til ->
.generic-widget-wrapper {
    padding-top: 0em;
    padding-right: 1em;
    padding-bottom: 0,4em;
    padding-left: 1em;
 }

Det ser også ud til, at der er ret meget padding under overskriften (h1).
Kan den halveres på tekstsiden eller noget i den stil?

**Comment by hyatt03** [comment]
@AndersFriisBrodsgaard Jeg tænker umiddelbart vi skal kigge på det samme tid, det vil gøre det en del nemmere 😄
