### ISSUE TITLE
Mobilvisning: Man kan ikke se antal følgere på gruppeoversigtsside

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#415]
Der er for lidt vertikal afstand mellem grupperne på https://biblo.dk/grupper i mobilvisning. Man kan ikke se antal følgere for den enkelte gruppe og "Vis flere"-knappen ligger for tæt på grupperne. 

![img_0007](https://cloud.githubusercontent.com/assets/18284484/19686344/f2b8cf6e-9ac0-11e6-9215-d4bb22527b5a.PNG)

![img_0008](https://cloud.githubusercontent.com/assets/18284484/19686415/55e0fcce-9ac1-11e6-860f-767dd63de0ce.PNG)

**Comment by KiraH** [comment]
testet OK
