### ISSUE TITLE
Profilbillede vender på hovedet

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#427]
https://biblo.dk/profil/49071

Er sikkert en manifestation af dette issue:
# 81

**Comment by AndersFriisBrodsgaard** [comment]
Kan evt. også bare skyldes at billedet er uploadet på hovedet...

**Comment by hyatt03** [comment]
Den er uploadet på hovedet:
https://biblo.dk/billede/7146/original

**Comment by AndersFriisBrodsgaard** [comment]
Fedt! Jeg lukker den igen.
