### ISSUE TITLE
Visning af en gruppes følgere i omvendt rækkefølge

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#43]
Visningen af en gruppes følgere skal være med nyeste følgere først: Først vises gruppeværten/ejer med tilhørende markering, dernæst skal gruppens følgere vises i kronologisk rækkefølge med de brugere, der senest er begyndt at følge gruppen, først.

**Comment by jacobandresen** [comment]
Jeg tror at jeg mangler info i datamodellen om hvornår en bruger er startet med at følge gruppen.

**Comment by AndersFriisBrodsgaard** [comment]
Det er altid samme rækkefølge profilerne vises i - hvad er det for en rækkefølge ?
Alternativt en random rækkefølge, dog altid med gruppeejer først.

**Comment by jacobandresen** [comment]
sorteringen er iøjblikket med de nyeste medlemmer først.  Dvs de medlemmer som senest har lavet en konto på biblo.dk .  Det bliver for besværligt at sortere på følge-tidspunktet for medlemmet på gruppen lige nu og her ... så jeg indsætter noget kode lister i tilfældig rækkefølge med gruppeejer først.

**Comment by KiraH** [comment]
https://biblo.dk/grupper/2
Det er kun 15 af de 94 følgere på gruppen, der vises random

**Comment by KiraH** [comment]
Hvis man går ind på siden og refresher, kommer der stadig kun en delmængde af gruppens følgere frem. Men hvis man klikker på "vis flere" ændres rækkefølgen og her ser det ud til at der vises en random rækkefølge af alle gruppens deltagere. @AndersFriisBrodsgaard det må være dit call om denne er løst.

**Comment by jacobandresen** [comment]
Jeg har rykket rundt i gruppevisningen sådan at alt data om gruppens følgere nu afleveres til klienten og at der nu sorteres tilfældigt der. Det burde udbedre problemet for nu.

**Comment by KiraH** [comment]
Yes, så er den der.
