### ISSUE TITLE
Biblo logo skiftes ud med "rigtig" svg

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#445]
Det nuværende logo er et bitmap, der er wrappet i en svg. 
Link til Dropbox med en rigtig vektor-svg, som skal erstatte det nuværende logo:
https://www.dropbox.com/s/j77o6sib4p15ib0/biblo_logo_100x30.svg?dl=0

**Comment by hrmoller** [comment]
Når denne issue er løst kan svg-sprite-loader sandsynligvis opgraderes til seneste version. jf. #692

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Filen der linkes til findes ikke længere.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo
