### ISSUE TITLE
Displayname kan ikke rettes tilbage

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#452]
Ved en fejl er et displayname for brugeren "vang" blevet rettet til noget andet. Det er dog ikke muligt at ændre det tilbage, hverken via frontend, admin eller explorer på CS. Servicen svarer tilbage at der allerede findes en bruger med det navn, men der kan ikke søges nogen frem. 
Nu hedder brugeren så i stedet "vang ". 

Brugerens profil er her:
https://biblo.dk/profil/29739

**Comment by AndersFriisBrodsgaard** [comment]
Skal muligvis overføres til et andet repository.

**Comment by hyatt03** [comment]
Vang har nu fået sit brugernavn tilbage.
