### ISSUE TITLE
Stjerner skubbes ned i widget - seneste anmeldelser

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#453]
Se dump. Fejlen skyldes mange linieskift i anmeldelsen. Se anmeldelsen her:
https://biblo.dk/anmeldelse/79300

![screenshot 2016-12-09 11 38 53](https://cloud.githubusercontent.com/assets/18284484/21046280/3b5f13a2-be04-11e6-8158-0beb8fe7b3bf.png)

**Comment by AndersFriisBrodsgaard** [comment]
Man kunne evt. fjerne linieskift i widgetvisningen.

**Comment by hrmoller** [comment]
Jeg har oprettet en SENESTE ANMELDELSER widget på forsiden af demo hvor de seneste anmeldelser pt. indeholder forskelligt antal af linjeskift, og dermed bør være et ok udgangspunkt for test.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo
