### ISSUE TITLE
Læsebevis til Sommerbogen på profil skal ikke vises på offentlig profil

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#46]
Knappen til læsebevis skal kun være synlig for brugeren selv, ikke for andre brugere, som kommer ind på brugerens offentlige profil.
https://biblo-dev.demo.dbc.dk/profil/5

**Comment by hrmoller** [comment]
Fixed med 9e2af06ec45893105e00fa6d51d1ab21d4647c1a
