### ISSUE TITLE
Styling på karussel fejler på iOS

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#466]
De enkelte bannere ligger oveni hinanden. Se nederst på forsiden af biblo-dev.

![file 16-12-2016 12 33 39](https://cloud.githubusercontent.com/assets/18284484/21261471/f054277a-c38b-11e6-8c93-faf77e6a16c3.png)

**Comment by hyatt03** [comment]
Jeg har lige testet på iphone 6, det ligner umiddelbart noget caching for jeg har ikke et issue her.

**Comment by hyatt03** [comment]
@AndersFriisBrodsgaard
