### ISSUE TITLE
"Indsæt anmeldelse"-knap på gruppeside skal være inaktiv udenfor åbningstiden

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#47]
Når det er udenfor åbningstid på Biblo, skal "Anmeldelse"-knappen i grupper (ved opret indlæg, opret  kommentar, rediger indlæg og rediger kommentar.
Knappen skal være inaktiv efter samme princip som "Upload"-knappen.

**Comment by KiraH** [comment]
testet OK
