### ISSUE TITLE
Titler på værkside er med stort begyndelsesbogstav i hvert ord

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#476]
Se fx her https://biblo.dk/materiale/870970-basis:27907504
Der skal ikke pilles ved titlerne, da de i udgangspunktet bør stå korrekt i brønden.

![screenshot 2017-01-02 14 18 55](https://cloud.githubusercontent.com/assets/18284484/21589846/6aa6cfd8-d0f6-11e6-8ea5-b5e13b7756bb.png)

**Comment by hyatt03** [comment]
Rettelse: De skal ikke stå som i brønden, de skal dog følge samme konvention ift. store og små bogstaver.

**Comment by KiraH** [comment]
testet OK
