### ISSUE TITLE
Læsebevis kan ikke håndtere emojis

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo#48]
Læsebevis kan ikke håndtere emojis:

--
![Screenshot_1](https://www.dropbox.com/s/beq525kio5eo2w4/Screenshot%202016-05-31%2008.55.39.png?dl=1)
--
![Screenshot_2](https://www.dropbox.com/s/i1equoajahdcoa5/Screenshot%202016-05-31%2008.58.13.png?dl=1)

**Comment by hrmoller** [comment]
Halvt fix. Emojis bliver erstattet med '' (tom streng). I en mere langsigtet bør vi nok se på om ikke vi skal generere en PDF fra en HTML siden istedet.

**Comment by KiraH** [comment]
testet OK
