### ISSUE TITLE
Gruppebillederne på "Grupper"-siden skal være kvadratiske

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#5]
Billederne for de enkelte grupper på "Grupper"-siden skal tvinges til at være kvadratiske ligesom på gruppens egen side. 
https://biblo.demo.dbc.dk/grupper

**Comment by jacobandresen** [comment]
Billederne er nu kvadratiske.

**Comment by jacobandresen** [comment]
fixet

**Comment by AndersFriisBrodsgaard** [comment]
Jeg kan se, at fejlen er genopstået på driftserveren.
https://biblo.demo.dbc.dk/grupper

**Comment by jacobandresen** [comment]
Vi bruger iøjeblikket kaldet "small-square" til at hente billedet.  Kaldet presser billedet sammen til et kvadrat så det kan vises på skærmen som et kvadrat. Det var jo det , der var meningen  - men det ser jo ikke godt ud ...  Jeg retter koden til , så den billedet fremvises på samme vis som på den enkelte gruppes side. På den måde vil der i enkelte tilfælde med aflange billeder blive skåret indhold fra billedet fra så det kan vises som et kvadrat.

**Comment by jacobandresen** [comment]
Nu er fixet ude på biblo.dk
