### ISSUE TITLE
Kommentarer forsvinder indtil reload af side ved ret i indlæg

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#50]
Når man retter i et indlæg, forsvinder kommentarerne til indlægget. De kommer først frem igen, når siden reloades. 
Kun testet på OSX Chrome

**Comment by jacobandresen** [comment]
Jeg bemærkede da @AndersFriisBrodsgaard at fejlen også optræder i produktion nu . Dvs at fejlen ikke er indtroducere ifm UploadMedia refactorerringen der er undervejs på udvikling lige nu.

**Comment by KiraH** [comment]
testet OK
