### ISSUE TITLE
Tilpasninger af PDF-upload

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#502]
- [x] Besked vises i indlæg, mens pdf tjekkes for virus: "Vent mens vi gør PDF'en klar til visning"
- [x] Når PDF'en er færdig med at uploade, skal den automatisk vises i indlægget uden at siden skal reloades (sockets)
- [x] Ændring af knap: Video-ikonet skal fjernes, så der er to ikoner: Kamera og fil. Knapteksten skal være “Billede / video / pdf”. Og tekst på begge knapper i desktop/tablet og ingen tekst på mobil. 
- [x] Når brugeren trykker "rediger" for et indlæg, hvor der er uploadet en pdf, skal pdf'en vises med mulighed for at slette - på samme måde som ved upload af et billede. 
- [x] Visning af indlæg med pdf i widget: Vis ikon for pdf. Se attachment

![screenshot 2017-02-02 13 38 23](https://cloud.githubusercontent.com/assets/18284484/22549702/edbaec10-e94c-11e6-9a62-877b7025b6ff.png)

**Comment by AndersFriisBrodsgaard** [comment]
Jeg kan ikke slette en pdf, jeg har uploadet (Safari OSX)
Knapper til upload og anmeldelse ved rediger indlæg, skal kun vises med ikoner, ellers er der ikke plads til dem i én linie. 

![screenshot 2017-03-02 09 12 31](https://cloud.githubusercontent.com/assets/18284484/23498628/ce7f5236-ff28-11e6-9c86-e9940d50cfa0.png)

**Comment by AndersFriisBrodsgaard** [comment]
Fedt med sletning af PDF.
Der skal dog lige fjernes tekst fra knapperne ved rediger indlæg (se tekst ovenfor). Jeg vil gerne have knapperne i én linie.

**Comment by KiraH** [comment]
testet OK
