### ISSUE TITLE
Video tilknyttes ikke til indlæg ved klik på OK.

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#51]
Når man uploader video på en langsom forbindelse, tilknyttes videoen ikke til indlægget med mindre man venter lang tid med at trykke OK efter at videoen er uploadet.
Når man trykker OK, får man spinner på OK-knappen i lang tid - fx over et minut - inden indlægget vises.
https://biblo.demo.dbc.dk/grupper/1
OSX Safari og Chrome

**Comment by jacobandresen** [comment]
Jeg kigger på det

**Comment by jacobandresen** [comment]
Jeg har indsat kode der skulle sikre at spinneren er aktiv mens videoen bliver uploadet. Imens spinneren er aktiv, så er det meningen at der ikke sker noget ved tryk på OK.

**Comment by Mariannedybkjaer** [comment]
Har forsøgt at uploade en video (25 MB) til en anmeldelse. Både i Chrome og FF forsvandt den grønne spinner hurtigt, men der står efter flere minutter stadig beskeden om at din video er ved at blive behandlet. Refresh af siden har ingen effekt. Fx på denne side https://biblo-dev.demo.dbc.dk/materiale/870970-basis:07313632

**Comment by KiraH** [comment]
jeg har også forsøgt mig lidt, men tænker at problemet måske snarere er biblo-dev på biblo.demo har jeg ikke problemer med upload

**Comment by jacobandresen** [comment]
Prøv gerne på biblo.demo. biblo-dev kan ikke snakke med amazon . Så skaleringen fejler. (dvs at der vil blive ved med at stå din video er ved at blive behandlet på biblo-dev).

**Comment by Mariannedybkjaer** [comment]
På biblo.demo får jeg samme resultat i FF. Altså besked om behandlingen forbliver på skærmen. I Chrome vises kun den grønne bjælke. Man kommer ikke hen til behandler-beskeden

**Comment by KiraH** [comment]
Hvor længe har du ventet? Der går lige lidt tid. Har du et link til din video?

**Comment by Mariannedybkjaer** [comment]
Ok, det tager godt nok lang tid! Ved ikke nøjagtig hvor meget, men nu er den der på dev. I drift på Chrome 3 minutter.
