### ISSUE TITLE
Man kan ikke oprette profil da der ikke kommer suggestions på bibliotek

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#529]
Når man skal oprette en profil på Biblo, *skal* man vælge et bibliotek vha. suggestions. Der kommer pt. ikke nogen suggestions, og det er derfor ikke muligt at oprette en profil. 
Nilex sagsnr. 53866

**Comment by vibjerg** [comment]
entity-suggest/library på xptest er stoppet med at fungere. Løses ved at skifte over på suggester i mesos. Er rettet i https://github.com/DBCDK/biblo-config
