### ISSUE TITLE
Når der ikke er forsidebillede på et værk, skal der vises samme fallbackbillede, som der benyttes i søgeresultatet.

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#53]
Fx for spil: https://biblo-dev.demo.dbc.dk/images/covers/game.png
Billedet skal bruges øverst i midten, som baggrundsbillede i topbaren og i højre spalte.
På vuværende tidspunkt benyttes følgende billede: 
https://biblo-dev.demo.dbc.dk/Billede-kommer-snart.jpg

**Comment by KiraH** [comment]
testet OK
