### ISSUE TITLE
Anmeldelser i indlæg vises ikke ved direkte link til indlæggene

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#539]
Fra en widget på fx forsiden af Biblo er der direkte links til indlæg. De indlæg, som indeholder anmeldelser viser ikke den vedhæftede anmeldelse, når man følger et direkte link. De vises fint, hvis man ser indlægget i den almindelige gruppekontekst.

Direkte link: https://biblo.dk/grupper/670/5725
![screenshot 2017-03-23 13 42 54](https://cloud.githubusercontent.com/assets/18284484/24248183/b7413ce0-0fce-11e7-8178-a539f9d710a4.png)

Visning af indlæg i gruppen: https://biblo.dk/grupper/670
![screenshot 2017-03-23 13 42 36](https://cloud.githubusercontent.com/assets/18284484/24248199/c8197a5a-0fce-11e7-9783-50d854764e38.png)

**Comment by KiraH** [comment]
testet OK
