### ISSUE TITLE
Widgets på forside af Biblo loader langsomt

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#548]
Biblo vil gerne have undersøgt hvad der gør, at widgets på forsiden loader langsomt.
Bruges der ikke nedskalerede billeder?
Er communityServicen ikke hurtig nok eller mangler der optimering?
Er det kald til admin, der ikke besvares hurtigt nok?

**Comment by vibjerg** [comment]
Det ser ud til at det er communityservicen der svarer langsomt. Især i peak perioder.

**Comment by vibjerg** [comment]
Man kan overveje om der skal laves cache af det enkelte widgets. Der er behov for forskellige cachetider.

**Comment by hyatt03** [comment]
Jeg har implementeret noget caching, jeg skal bruge feedback på om det skal være mere aggressivt.

**Comment by hyatt03** [comment]
- [ ] Brug varnish til at cache cloudfront urler
- [ ] Tænd for statistik på postgres
- [ ] Brug charles til at undersøge dublet kald
- [ ] Kig på sql fra loopback til at lave bedre indeksering
- [ ] Send cache headers på billeder 
- [ ] Flere kerner
