### ISSUE TITLE
Fanerne aktiviteter og anmeldelser tydeligere

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#55]
Teksten på fanerne aktiviteter/anmeldelser kan med fordel være tydeligere

**Comment by hrmoller** [comment]
Det er vel ikke rigtig en bug? Jeg synes vi skal have en US på det istedet.
cc. @kkdbc @AndersFriisBrodsgaard

**Comment by AndersFriisBrodsgaard** [comment]
Der skal en anden font på og andre farver på faneblads teksterne + mere padding. Der er lavet design på  det. 
![faneblade_profil](https://cloud.githubusercontent.com/assets/18284484/15710928/5e1d534c-280c-11e6-8c55-8923b1a66d69.png)

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Hvilken font er det?

**Comment by AndersFriisBrodsgaard** [comment]
Fredoka One, en af de tre google fonte, vi bruger.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK
