### ISSUE TITLE
Gruppebilleder skaleres forkert

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#559]
Igen-igen...
Billeder, der bruges på gruppesiden, som gruppens profilbillede, og det samme billede, der optræder i diverse widgets er skaleret forkert. De skal beskæres, så de er kvadratiske, ikke skaleres til at være kvadratiske.

Eksempel på gruppbillede: https://biblo.dk/billede/11100/small-square
Ikke skaleret version: https://biblo.dk/billede/11100/medium

Gruppe ses her:
https://biblo.dk/grupper/877

**Comment by hyatt03** [comment]
Skaleringen virker fint, det her var et billede fra før vi fiksede det sidst, jeg har gennemløbet billederne og omskaleret dem.

**Comment by AndersFriisBrodsgaard** [comment]
Cool, mange tak.

**Comment by AndersFriisBrodsgaard** [comment]
Der er dog problemer med at skalere animerede giffer. Se fx https://biblo.dk/grupper/309

Bør se sådan her ud:

![giphy](https://user-images.githubusercontent.com/18284484/29044317-301ba00e-7bbf-11e7-8875-829a7c45637e.gif)
