### ISSUE TITLE
Mgl fejlbesked hvis man ikke markerer ved lån af poster med kun en mattype

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#56]
Når man låner et materiale med kun en enkelt type, får man ikke en fejlbesked hvis man prøver at bestille uden at have valgt materiale. Og det kommer man let til netop fordi der kun er en materialetype

**Comment by fvsdbc** [comment]
Fejlbesked hvis man ikke vælger et materiale. Hvis der kun er et materiale, skal det være valgt og så kan der ikke komme nogen fejlbesked

**Comment by KiraH** [comment]
testet OK
