### ISSUE TITLE
Post kan ikke bestilles - fejler i bestilflowet

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#560]
Man får en fejlmeddelelse, når man forsøger at bestille bogen "Besynderlige bæster":
https://biblo.dk/materiale/870970-basis:28414005
(I hvert fald en bruger og jeg selv får fejlbeskeden:
"Du kan desværre ikke låne denne bog.
Prøv at spørge på dit eget bibliotek, om de kan hjælpe dig med at låne den på en anden måde."

Jeg kan godt bestille bogen på bibliotek.dk

**Comment by hyatt03** [comment]
Bug i serviceprovideren (https://github.com/DBCDK/serviceprovider/issues/717)
