### ISSUE TITLE
Optimering af gruppesider

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo#566]
Hver gang der hentes en gruppe, hentes samtlige følgere af gruppen ud af databasen. Dette sker for at finde antal følgere til en gruppe, men har vist sig at være meget ressourcekrævende, især på gruppeoversigtssiden. 

Problemet ligger delvist i communityservicens count property, som henter alle profiler og laver en optælling. Vi kan vælge at løse det i biblo ved at benytte count endpointet for hver gruppe i stedet.

Der kan dog være et problem med at slettede profiler tælles med.

**Comment by AndersFriisBrodsgaard** [comment]
Der vises et tilfældigt udvalg af følgere i boksen "Følgere" i højrespalten. For at vælge tilfældigt blandt alle følgere, hentes alle brugere først ud. Det kan nok også gøres smartere.

**Comment by hrmoller** [comment]
Efter aftale med @AndersFriisBrodsgaard 
Er fokus i første om gang på enten en gruppeside eller gruppeoversigten, hvor hentning af indhold og count splittes op i to separate kald.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo
