### ISSUE TITLE
Tidsangivelse for indlæg ændres fra dage til måned og derefter til dato

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#567]
Gælder også for kommentarer og anmeldelser.
Når det er 15 dage siden, skrives i stedet dato efter formen 13. juni 2017
EX:

![screenshot 2017-06-29 11 36 29](https://user-images.githubusercontent.com/18284484/27683058-100b7564-5cc5-11e7-86c6-47f8d0634c53.png)

**Comment by hrmoller** [comment]
Overskrift og beskrivelse er lidt tvetydig. Jeg har lavet det sådan at er en post/comment/review 16 dage eller derover vil der stå dato. Eks. 12. juli 2017

**Comment by AndersFriisBrodsgaard** [comment]
Cool, det var også det, jeg mente :-)
