### ISSUE TITLE
Når man skriver den første anmeldelse for et værk, vises anmeldelsen ikke

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#573]
Har lavet en anmeldelse for et værk
https://biblo.dk/materiale/870970-basis%3A05205360
Anmeldelsen vises ikke efter at den er lavet, heller ikke i en anden browser.
Kan det have noget med caching at gøre?

![screenshot 2017-07-03 13 00 25](https://user-images.githubusercontent.com/18284484/27790214-e1ab74b6-5fef-11e7-883f-e1903de11321.png)

**Comment by hrmoller** [comment]
Tilføjer metode på dbc-node-serviceprovider til invalidering af cache(https://github.com/DBCDK/dbc-node-serviceprovider/issues/18) og implementerer derefter i Biblo
