### ISSUE TITLE
Boks med "Alle bøger i serien"

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#574]
Tilføj boks med visning af alle bøger i serien. I boksen skal der som default vises 6 værker. Styling som i boksen med visning af alle bind i et flerbindsværk.

Boksen skal placeres øverst i højre spalte - samme sted som flerbindsværk-boksen. De to bokse vil ikke skulle vises på samme side - enten er værket en del af et flerbindsværk eller en del af en serie.
Under hvert værk vises nummer i formen "1. bog", "1. CD", "1. spil", "1. film"

![desktop-vaerkside-alle-boger-i-serien](https://user-images.githubusercontent.com/18284484/27910355-28b3e912-6255-11e7-890b-fb405c9598d8.png)

**Comment by AndersFriisBrodsgaard** [comment]
Der er problemer med visninger i nogle tilfælde, fx Tintin:
- nogle værker vises med nummerangivelse og andre med titel. 
- der er flere værker med samme nummerangivelse. Ser ud til at skyldes, at det kun er det sidste ciffer af tocifrede nr., der vises.

Se fx:
 https://biblo.dk/materiale/870970-basis:25418689

**Comment by hrmoller** [comment]
- [ ] fix regex
- [ ] fix visning af titel

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo. 
Problemerne med visningen af rækkefølge på tintin-serien skyldes inkonsistent metadata.
