### ISSUE TITLE
iPhone 5s - Grupper - Indsæt anmeldelse?

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#59]
Klikker i Gruppe i kommentarfelt på ikon for anmeldelse. Får en besked: ” Indsæt anmeldelse. Vi kunne ikke finde nogen anmeldelse, prøv at oprette en ny! ” Jeg klikker på OK, og kommer tilbage til kommentarfeltet – vil det sige at jeg så skal skrive en anmeldelse af gruppen? Jeg forstår ikke funktionen når jeg er i Grupper?

**Comment by fvsdbc** [comment]
Hvis du har lavet en (eller flere) anmeldelse(r), vises en liste af dem, som du kan vælge fra - Knappen Anmeldelse og den tilhørende ikon er måske ikke klar nok

![indset_anmeldelse](https://cloud.githubusercontent.com/assets/3070049/17205204/04c923d2-54aa-11e6-8345-c5285514f9cf.png)

**Comment by AndersFriisBrodsgaard** [comment]
Er ikke en bug. Men flowet omkring indsættelse af anmeldelse skal muligvis forbedres, så brugeren forstår, hvad der foregår.
