### ISSUE TITLE
Fejl v lånernummer

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#595]
Henvendelse:   "Hun er logget ind med sit uni login og skal så oprette en profil.  Når vi kommer til "dit lånernummer" så uanset hvad der skrives i det felt, så skriver den "Brug det brugte format".  Selv hvis vi vælger den kode, som der vælges for os, får vi samme fejl."
De bruger Mac. Se vedlagte.
![lanernummer](https://user-images.githubusercontent.com/1375270/28054427-1314b064-6615-11e7-863e-20d8e3862b4a.JPG)
Kender I den fejl?

**Comment by hyatt03** [comment]
Skriver hun andet end tal?

**Comment by hyatt03** [comment]
Begge felter forventer tal

**Comment by AndersFriisBrodsgaard** [comment]
Lukker, har ikke hørt mere fra brugeren
