### ISSUE TITLE
Fejl hvis man bruger Enter i søgning

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#596]
Jeg skriver et søgeord og trykker Enter i stedet for at trykke på Søg. Får UPS...

Du har ramt en side der ikke findes. Gå tilbage til den foregående side eller brug menuen til at komme videre.

500 Der er sket en fejl

**Comment by hyatt03** [comment]
hvilket søgeord?

**Comment by Mariannedybkjaer** [comment]
Kan ikke genskabe det. Lukker.
