### ISSUE TITLE
Fejl ved anmeldelse

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#606]
En bruger får fejl, når hun OK'er efter en anmeldelse. Jeg har prøvet at anmelde samme bog, no problemos. Se vedlagte.
![fejl_v_anm](https://user-images.githubusercontent.com/1375270/28267322-ef64dd58-6af9-11e7-97fc-0a501843d05d.png)

**Comment by AndersFriisBrodsgaard** [comment]
Brugeren har oprettet en ny profil og har ingen problemer nu.
