### ISSUE TITLE
Søgninger er case-sensitive

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#613]
Søgning på "Pippi" giver resultat, mens søgning på "pippi" ikke gør:
https://biblo.dk/find?q=Pippi&grupper=0&emneord=&materialer=
https://biblo.dk/find?q=pippi&grupper=0&emneord=&materialer=

**Comment by AndersFriisBrodsgaard** [comment]
Lukker - åbenbart et midlertidigt problem i relation til fejl på underliggende services.

**Comment by AndersFriisBrodsgaard** [comment]
Er sandsynligvis et problem med caching - er opstået igen 10. august

**Comment by kfudbc** [comment]
Er sandsynligvis relateret til https://github.com/DBCDK/serviceprovider/pull/756

**Comment by AndersFriisBrodsgaard** [comment]
Fejlen er væk igen, fikset med serviceprovider issue. Lukker
