### ISSUE TITLE
iPhone 5s - Søgning - søger på Green, men finder ikke John Green (flænge i himlen)

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#62]
Jeg forventede hurtigt at få John Green (en flænge i himlen) op blandt første hits, men finder ham ikke? Hvad sorteres der mon efter? Opgiver efter at have bladret mange gange.

**Comment by kkdbc** [comment]
rankering skal tilføjes, tages op senere

**Comment by AndersFriisBrodsgaard** [comment]
Vi kan evt. lige tjekke en gang mere, hvilken rankering, vi benytter. Det skulle gerne være rank_frequency

**Comment by hrmoller** [comment]
rank_frequency er default: https://github.com/DBCDK/biblo/blob/master/src/server/serviceProvider/transformers/OpenPlatform/search.transform.js#L19

**Comment by fvsdbc** [comment]
Søgningen finder flg. vægte:
dkcclterm.ti:  2054 (1027*2)
dkcclterm.fo: 714 (714*1)
dkcclterm.em: 18 (3*6)
og vælger rankering efter titel - rankeringsmæssigt er det uheldigt at hedde Green, eller London

**Comment by AndersFriisBrodsgaard** [comment]
Lukker
