### ISSUE TITLE
Tegn bliver "spist" ved indtastning i søgefeltet i IE-browser

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#623]
Ved indtastning i søgefeltet skal man skrive meget langsomt, ellers forsvinder tegnene. (Det virker som om tegnet vises kort, men at cursoren så hopper en gang tilbage.
Se billedet hvor du skulle stå QWERTY gentagende gange. 

![bibloie](https://user-images.githubusercontent.com/28528078/28922199-6fe99bc8-7859-11e7-8ba8-f779500e8e72.JPG)

Testet med IE11 - Version 11.1066.14393.0 på WIN10.

**Comment by hrmoller** [comment]
@BettinaAndersen jeg vil forvente at det kan fikses med en udrulning, jeg kan i hvert fald ikke reproducere fejlen på biblo.demo.dbc.dk.

**Comment by AndersFriisBrodsgaard** [comment]
@BettinaAndersen vil du ikke teste denne, når du er tilbage fra ferie? Browserstack er for langsomt til at jeg kan teste det.

**Comment by BettinaAndersen** [comment]
Har ikke set ovenstående kommentar, sorry. Men har testet nu, og det virker super!:)

**Comment by AndersFriisBrodsgaard** [comment]
Fedt :-)
Lukker
