### ISSUE TITLE
iPhone 5s - Søgning - hvis jeg vælger fra dropdown optræder en søgekode 

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#64]
Hvis jeg vælger fra dropdown i søgebox, laves der en videresøgning som indeholder søgekode term.creator=john green (f. 1974)

**Comment by KiraH** [comment]
hvad hvis du vælger en titel? Så skulle den gerne gå ind på et værk og ikke lave en søgning på creator

**Comment by lho** [comment]
ja, det var fordi jeg valgte en forfatter, at den skrev term.creator..

**Comment by KiraH** [comment]
forfattere er taget ud af suggest(drop down) så det vil ikke optræde mere. Jeg lukker denne.
