### ISSUE TITLE
Like af anmeldelse virker ikke

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#649]
Når man forsøger at like en anmeldelse, sker der ikke noget. Der er rollover på hjertet, men ved klik ændres hverken farven på hjertet eller antal af likes. Der er heller ikke ved reload af siden registreret nogen likes. 
Fejlen er både på demo og drift
Jeg har fx liket denne anmeldelse på drift: 
https://biblo.dk/anmeldelse/94980
og denne på demo:
https://biblo.demo.dbc.dk/materiale/870970-basis:21085081

Begge likes ca. kl. 14.55 25.aug 2017.

**Comment by kfudbc** [comment]
Har rettet fejlen i forhold til at den opdaterer når man trykker på hjertet. Der er dog stadig cache-problemer når man opdaterer siden.

**Comment by AndersFriisBrodsgaard** [comment]
Fino, lad os rulle ud i morgen tidlig.
