### ISSUE TITLE
Samme indhold vises i to widgets af samme type

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#653]
Når man lægger to widgets af typen "Editorially selected materials" på en side, viser de det samme indhold, selv om der er specificeret forskelligt indhold i admin-grænsefladen.
Se de to widgets på https://biblo.demo.dbc.dk med overskrifterne "REDAKTIONENS FAVORITBØGER" og "EDITORIALLY SELECTED MATERIALS":
![screenshot 2017-08-31 14 44 23](https://user-images.githubusercontent.com/18284484/29923756-ee444bdc-8e5a-11e7-9e9e-83a20cda136e.png)

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Jeg fixet den her og merget til master så den burde være klar til test på demo.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo
