### ISSUE TITLE
Biblo skal kunne benytte moreinfo 2.9

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#655]
Biblo skal kunne benytte openplatforms default version af moreinfo - 2.9.

Når den kan det, skal biblos konfiguration til dåp ændres, så konfigurationen af moreinfo tages ud.

**Comment by KiraH** [comment]
Fejlen i moreinfo er rettet i version 2, så sættes Biblo til at benytte version 2, burde det virke.

**Comment by AndersFriisBrodsgaard** [comment]
Dette løses ved at Biblo går over til openPlatform 2.0
