### ISSUE TITLE
To "Best rated" widgets får siden til at crashe

### ISSUE THREAD

**Issue by Klausstovring** [DBCDK/biblo#657]
Der er lige nu en widget til bedst anmeldte bøger på siden "Frontpage". Hvis man laver en widget magen til, men krydser af i fx film, så den kun viser de bedst anmeldte film, så går hele siden ned og viser kun footeren.

**Comment by hrmoller** [comment]
@Klausstovring @AndersFriisBrodsgaard har I mulighed for at lave et eksempel på staging så jeg kan reproducere fejlen?

**Comment by AndersFriisBrodsgaard** [comment]
Lige nu crasher siden ikke, men de to widgets viser samme indhold på trods af, at de er defineret forskelligt i admin. Altså svarer det til #653 
Se https://biblo.dk/test-sektionsside

**Comment by AndersFriisBrodsgaard** [comment]
Har lavet et eksempel på staging her: 
https://biblo.demo.dbc.dk/section-page
Der ligger to best rated works widgets nederst på siden.

**Comment by AndersFriisBrodsgaard** [comment]
@hrmoller vil du kigge på den igen?

**Comment by hrmoller** [comment]
Jep gør det som det næste medmindre der kommer mere til #620 som jeg skal kigge på først.

**Comment by hrmoller** [comment]
Ser fortsat ud til at skyldes en fejl i https://github.com/DBCDK/biblo-admin. Jeg har efter aftale med @vibjerg oprettet denne issue: https://github.com/DBCDK/biblo-admin/issues/199

**Comment by vibjerg** [comment]
Fejlen i admin ser ikke ud til at være relateret til dette issue, men skyldes udelukkende at ikke alle felter til widgetten var udfyldt.

**Comment by vibjerg** [comment]
Det ser dog ud til at der ikke er noget issue med 2 "best rated" widgets, men at det blot har skyldes forkert konfiguration. Jeg har oprettet https://github.com/DBCDK/biblo-admin/issues/200 så problemet ikke kan opstå.

**Comment by AndersFriisBrodsgaard** [comment]
Cool. Lukker dette issue.
