### ISSUE TITLE
Best rated works widget viser intet indhold

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#659]
Widget'en Bedst anmeldte værker på https://biblo.dk/boger viser ikke noget indhold. Den har tidligere virket og der er ikke ændret på widget-indstillingerne i admin.

<img width="1101" alt="screenshot 2017-09-13 13 29 39" src="https://user-images.githubusercontent.com/18284484/30375357-821dbe9c-9888-11e7-8c3f-b5ac80a786b0.png">

**Comment by jacobandresen** [comment]
Lige nu ser det ud til at virke. Jeg er ikke logget ind på sitet (da jeg mangler uni-login ..)

**Comment by hrmoller** [comment]
@AndersFriisBrodsgaard Jeg kan ikke reproducere den. Kan du verificere fejlen stadig eksistere?

**Comment by AndersFriisBrodsgaard** [comment]
Den eksisterer ikke pt. Var sandsynligvis knyttet til fejl i openSearch. Lukker.
