### ISSUE TITLE
Ved sletning af anmeldelse står der stadig "Se din anmeldelse" på knappen.

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#66]
Når man trykker på "Se din anmeldelse" efter at have slettet anmeldelsen, går siden i stå. 

Der bør stå "Lav en anmeldelse" på knappen, og knappen skal vise inputfelt osv. til at skrive en ny anmeldelse. 

Når man reloader siden, vises knap osv. korrekt.

**Comment by KiraH** [comment]
testet OK
