### ISSUE TITLE
Test af anmelderside og estimat af mangler

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#661]
Det skal vurderes hvad der mangler for at den aftalte udviklingsopgave omkring anmelderside (AFB) kommer i mål.
Det skal estimeres hvad manglerne vil tage i tid. (KFU)

**Comment by AndersFriisBrodsgaard** [comment]
KFU estimater:
(3t)  Særlige konfigurationer giver tomt resultat, fx hvis man vælger "sjove bøger", "dark fantasy".
(1t)  HTML i beskrivelse skal decodes.
(2t)  Re-indeksering af anmeldelser, så ældre anmeldelser får knyttet genrer/emner til sig.
(10t) URL links. Browser-adresse-feltet skal opdateres til at passe med hvordan anmeldelsessiden er konfigureret - så man kan linke til en given konfiguration.
(2t)  Visning i mobil-format, samt i forskellige browsere skal tjekkes (firefox, IE)
(2t)  Tryk på anmeldelses-tekst skal føre til anmeldelses-side. Tryk på cover skal føre til værk-side.
(0,1t) Fjern hånd-cursor over stjerner
(3t)  Implementering af forskellige sætningskonstruktioner i filter-feltet øverst. Se #593.
(0,5t) Genre-dropdown skal vises alfabetisk a-å
(5t) Mulighed for at loade flere anmeldelser vha. vis flere-knap nederst på siden
(0,2t) Indsæt baggrundsbillede i filterområde: https://www.dropbox.com/s/w4r92ch8d9y5b75/topbanner-baggrund.png?dl=0
(0,1) Lidt "kortere" dropshadow på forsidebillederne 2px 2px i stedet for 5px 5px
(0,2) Sidetitel skal være "Anmeldelser - Biblo.dk"
(0,5t) Vis kun unikke likes

Total: 29,6 timer
