### ISSUE TITLE
Anmeldelses-side - resterende opgaver

### ISSUE THREAD

**Issue by kfudbc** [DBCDK/biblo#662]
- [x] Særlige konfigurationer giver tomt resultat, fx hvis man vælger "sjove bøger", "dark fantasy".
- [x] HTML i beskrivelse skal decodes.
- [x] Re-indeksering af anmeldelser, så ældre anmeldelser får knyttet genrer/emner til sig.
- [x] URL links. Browser-adresse-feltet skal opdateres til at passe med hvordan anmeldelsessiden er konfigureret - så man kan linke til en given konfiguration.
- [x] Visning i mobil-format, samt i forskellige browsere skal tjekkes (firefox, IE)
- [x] Tryk på anmeldelses-tekst skal føre til anmeldelses-side. Tryk på cover skal føre til værk-side. 
- [x] Fjern hånd-cursor over stjerner
- [x] Implementering af forskellige sætningskonstruktioner i filter-feltet øverst. Se #593.
- [x] Genre-dropdown skal vises alfabetisk a-å
- [x] Mulighed for at loade flere anmeldelser vha. vis flere-knap nederst på siden
- [x] Indsæt baggrundsbillede i filterområde: https://www.dropbox.com/s/w4r92ch8d9y5b75/topbanner-baggrund.png?dl=0
- [x] Lidt "kortere" dropshadow på forsidebillederne 2px 2px i stedet for 5px 5px
- [x] Sidetitel skal være "Anmeldelser - Biblo.dk"
- [x] Vis kun unikke likes

**Comment by BettinaAndersen** [comment]
Testet ok
