### ISSUE TITLE
Adgang givet til anonym bruger skal måske have en bedre løsning.

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#675]
Tidligere fejl med manglende forside skyldtes nægtet adgang till Biblo-admin. Dette er løst midlertidig ved at give anonym bruger adgang. Da det kun drejer sig om læserettigheder er det måske ok, men dette skal vurderes og muligvis skiftes ud med en mere korrekt løsning.

**Comment by vibjerg** [comment]
Der er umiddelbart ikke nogen problemer i at give anonyme brugere adgang til at hente indhold via admin. Det er indhold som i forvejen er tilgængelig via sitet. Det kunne dog give mening at oprette en særskilt bruger, som benyttes til at hente data ud. Denne bruger bør ikke være admin, men blot godkendt bruger.

**Comment by vibjerg** [comment]
Det er sandsynligvis en bug i drupal, som har skabt problemet, og det kan muligvis løses ved at opdatere til nyeste version af drupal. Det er ikke lykkedes mig at genskabe problemet lokalt eller på biblo-dev

**Comment by vibjerg** [comment]
Drupal og plugins opdateres til seneste version. https://github.com/DBCDK/biblo-admin/issues/193

**Comment by KiraH** [comment]
Lukker denne, DBCDK/biblo-admin#193 skal testes for at se om opdates virker som de skal.
