### ISSUE TITLE
Estimat: Biblo på DÅP V.2

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#677]
Biblo skal flyttes over på DÅP version 2 og bør samtidig opdateres i forhold til Bestil-funktionaliteten.
Dette issue omhandler kun estimat af opgaven.

**Comment by vibjerg** [comment]
Estimat af hvad det kræver at løse #663

**Comment by AndersFriisBrodsgaard** [comment]
Estimat er sendt til Bettina
