### ISSUE TITLE
Adgang til opensearch virker ikke på biblo.demo

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#679]
Hele søgesiden fejler:
https://biblo.demo.dbc.dk/find?q=hest&grupper=0&emneord=&materialer=

**Comment by AndersFriisBrodsgaard** [comment]
Opsætning af smaug skal ændres, så demo bruger den rigtige version - staging.

**Comment by KiraH** [comment]
Det er nu rettet og demo kan igen tilgå opensearch
