### ISSUE TITLE
Chrome: Ebøger bestilles, linker ikke til Ereolen

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#68]
Fx hvis man vil låne https://biblo-dev.demo.dbc.dk/materiale/870970-basis:25933915#! på ebog bestiller man. Åbner ikke ereolen

**Comment by jacobandresen** [comment]
Gider du teste igen? Vi havde noget knas med tokens og openplatform tidligere idag. Når jeg bestiller nu på det link du angav ovenfor, så viderestilles jeg til ereolen (testet på chrome)

**Comment by Mariannedybkjaer** [comment]
Det fejler stadig på Chrome. Har optaget det på en lille film - sender den til jacob på slack.

**Comment by KiraH** [comment]
Det virker heller ikke for mig.

**Comment by jacobandresen** [comment]
Jeg har et fix undervejs her der gerne skulle virke i flere browsere: https://github.com/DBCDK/biblo/commit/af3fb0dbe66983eb1435695222bff1570e9e0706 :=)

**Comment by Mariannedybkjaer** [comment]
Ser ud til at virke nu på dev på Chrome :-)
