### ISSUE TITLE
howru endpoint 

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#686]
UX ønsker et howru endpoint til Biblo a la:
Den på content-first - se nederst

Endpointet skal svare om den er OK, baseret på om den kan nå alle de services den benytter.

I hvor høj grad skal den også checke om den kan få et brugbart svar tilbage?

Det ville være smart om endpointet kunne trække info om de benyttede services fra sin konfiguration, om end det måske bliver lidt besværligt med den konfiguration Biblo har. 

Som default benyttes konfiguration default under node_modules/@dbc.dk, desuden overskrives med filen navngivet som NODE_ENV variabel, som kan findes i community.env filen i den byggede kode.

Der skal tjekkes på services:
Openplatform.dbc.dk - skal det også tjekkes om man kan trække et token?
Auth.dbc.dk
CommunityService
Bibloadmin - og om der kan hentes indhold ud herfra. (Man bør også tjekke at man ikke får {message: ""} på forsiden, da dette indikerer at man ikke har adgang)
Elasticsearch?

Opbygges som denne:
```json
{
  "ok": true,
  "services": [
    {
      "service": "database",
      "ok": true
    },
    {
      "service": "smaug",
      "ok": true
    },
    {
      "service": "hejmdal",
      "ok": true
    }
  ],
  "version": "0.1.0",
  "config": {
    "auth": {
      "url": "https://auth.dbc.dk"
    },
    "login": {
      "url": "https://login.bib.dk"
    },
    "migrations": {
      "directory": "src/migrations"
    },
    "seeds": {
      "directory": "src/seeds"
    }
  }
}}

**Comment by hrmoller** [comment]
Både borchk og EntitySuggest er konfigureret men ser ikke ud til at blive brugt direkte men via OpenPlatform. Er der nogen der kan be-/afkræfte det?
Der er vel ingen grund til at lave et howru-check på dem hvis de ikke bruges af Biblo - eller at de overhovedet figurerer i konfigurationen for den sags skyld?

**Comment by hrmoller** [comment]
EntitySuggest bruges ifm. søgning på bibliotek på profil siden.

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK i produktion
