### ISSUE TITLE
Opdatering af node + dependenices

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/biblo#692]
Node og mange dependencies er outdated og bør såvidt muligt opdateres.
~Liste med checkboxes kommer asap.~

__dependencies__
- [x] node => helst seneste LTS (pt. 8.9.1) ellers 6.x.x (pt. 6.12.0) som minimum
- [x] autoprefixer
- [x] autosize
- [x] babel-loader _(seneste 6.x.x pga. breaking changes)_
- [x] body-parser
- [x] bull
- [x] cache-manager-redis
- [x] compression
- [x] connect-redis
- [x] css-loader
- [ ] dbc-node-logger _(seneste version fungere ikke med nuværende setup hvor der logges til Kafka)_
- [x] express
- [x] express-session
- [x] express-validator
- [x] extract-text-webpack-plugin
- [x] newrelic
- [x] normalize.css
- [x] passport
- [x] passport-unilogin
- [x] postcss-loader
- [x] primus
- [x] react
- [x] react-addons-test-utils
- [x] react-dom
- [x] react-redux
- [x] redux
- [x] socketcluster (^8.0.2)
- [x] susy _(låst til version 2.2.12 da 3.x.x har mange breaking changes)_
- [x] svg-inline-loader
- [ ] svg-sprite-loader _(seneste version er ikke umiddelbart kompatibel med Biblo, idet farven i logoet ryger hvis der opgraderes til nyeste version)_
- [x] weback
- [x] ws
- [x] teaspoon _slettet - erstattet med enzyme_

__devDependencies__
- [x] babel-eslint
- [x] chai
- [ ] cucumber _(nyeste version knækker nuværende setup. Indtil #694 er afklaret er der ikke grund til at opdatere)_
- [x] eslint
- [x] eslint-plugin-react
- [x] expect
- [x] jsdom
- [x] jsdom-global
- [x] karma-jsdom-launcher
- [x] mocha
- [x] parallelshell ~_(bliver det overhovedet brugt?)~ parallelshell er fjernet da det ikke bruges_
- [x] sinon
- [ ] skin-deep _(nyeste version knækker nuværende setup. På sigt kunne [enzyme](https://github.com/airbnb/enzyme) overvejes som alternativ for skin-deep ~og teaspoon~)_
- [x] wallaby-webpack _alt vedrørende wallaby er fjernet da ingen bruger det_

**Comment by AndersFriisBrodsgaard** [comment]
OK, lukker
