### ISSUE TITLE
Analyse af cookie-fejl i IE 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#695]
Hvad skabte den fejl i IE, som gjorde at man ikke kunne fjerne cookie-feltet. Og kan vi  gøre noget for at sikre, at det ikke sker igen.

**Comment by hrmoller** [comment]
[Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) findes ikke IE11 plus visse andre browser(versioner) så derfor inkluderes der et såkaldt polyfill i koden der sikrer at de browsere der ikke har eks. Promise stadig kan afvikle koden, i det her tilfælde Biblo.

Hvis der et eller andet sted i CI-setuppet omkring Biblo var afvikling af seleniumtests mod en IE11 browser ville fejlen være fanget.
Der er allerede tests der sikrer, at der vises en cookie warning og at den kan lukkes, de bliver bare ikke kørt mod IE11 - eller andre browsere for den sags skyld. Kun (en aldrende version af) Chrome headless.
