### ISSUE TITLE
https skal fjernes på Biblo's billeder fra moreinfo - flere steder

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#707]
Hvis Biblo skal kunne bruge moreinfo 2.10 og 2.11 på anmeldelsessiden skal https fjernes, det kommer med 2 gange nu og gør at billeder ikke vises.

Se forsidebillede f.eks her: https://biblo.demo.dbc.dk/anmeldelse/89

Samme fejl på søgeresultat: https://biblo.demo.dbc.dk/find?q=harry&grupper=0&emneord=&materialer=book

Og materialeside: https://biblo.demo.dbc.dk/materiale/870970-basis:22433547

**Comment by AndersFriisBrodsgaard** [comment]
Testet OK på demo
