### ISSUE TITLE
iPhone 5s - Profil - kan ikke lukke den røde box ved ved klik på x

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#71]
Hvis jeg klikker på mit profilfoto, får jeg en rød box, den kan jeg ikke få væk igen med klik på kryds i øverste højre hjørne. Kan kun får den væk ved at klikke på Profil eller Logud.

**Comment by fvsdbc** [comment]
Har ikke adgang til en Iphone 5 og browserens emulering, har ikke noget problem med at lukke boxen

**Comment by lho** [comment]
virker nu

**Comment by fvsdbc** [comment]
Man skal være utroligt præcis for at ramme de 5 pixel man har i højden.

Har forsøgt at gøre området større, så man ikke skal "føle" sig frem.

**Comment by AndersFriisBrodsgaard** [comment]
Lukker
