### ISSUE TITLE
iPhone 5s - Profil - Anmeldelsesforsider mangler (der står Other) og Henter data

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#72]
Mine anmeldelser under Min profil – der står Orher, der hvor der skulle være forside og Henter data ved siden af forsiden.

**Comment by hrmoller** [comment]
Jeg kan ikke reproducere ovenstående og det passer også nogenlunde med nedetid på OpenPlatform så det skal nok lige testes igen.

**Comment by AndersFriisBrodsgaard** [comment]
Det ser ud til, at fejlen kun er for Lauras profil:
https://biblo-dev.demo.dbc.dk/profil/12#ANMELDELSER
Men det fejler også når andre kigger på hendes profil.

**Comment by AndersFriisBrodsgaard** [comment]
@lho Vil du ikke teste den her igen?

**Comment by lho** [comment]
Har testet på https://biblo-dev.demo.dbc.dk/profil - det ser fint ud nu.

**Comment by AndersFriisBrodsgaard** [comment]
Super, vi lukker den igen
