### ISSUE TITLE
Manglende søgeresultater ved søgning 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#732]
Der er problemer med at søge på Biblo, som minder om de udfordringer der tidligere har været med de tomme poster. Nedenstående illustrerer, men der er flere eksempler.
Eksempel: Kan slet ikke søge på serien "Wimpy kid". Hvis der søges på undertitlen "Ikke en dagbog", fås nogen gange et resultat, andre gange ikke.
![image](https://user-images.githubusercontent.com/28528078/36307432-699df0e4-131c-11e8-9a21-715e09247e01.png)
![image](https://user-images.githubusercontent.com/28528078/36307442-73d24a24-131c-11e8-9407-0335e4096696.png)

Andre eksempler har været Vildheks og Sporløst.

Det er ikke lykkes mig at finde manglende poster som ikke er serie/flerbindsværk, men ved ikke om det er et tilfælde.
Det er ikke lykkes mig at se lignende problemer på bibliotek.dk.

**Comment by BettinaAndersen** [comment]
For at udelukke "Manukkerne"som skyldig, bør vi prøve at bruge OS 5.0 på staging.

**Comment by KiraH** [comment]
Har forsøgt at sætte OS 5.0 på, men sitet kan slet ikke køre med den version. Sitet kører stadig mod brønd 3.5 i den søgning det benytter pt, så måske er det problemet?

**Comment by KiraH** [comment]
Der er problemer med at søge gennem DÅP med v5.0:

{
  "statusCode": 200,
  "data": [],
  "error": [
    "Parse error: briefDisplay could not be found on object: 870970-basis:29567085",
    "Parse error: briefDisplay could not be found on object: 870970-basis:25862899",
    "Parse error: briefDisplay could not be found on object: 870970-basis:53296386",
    "Parse error: briefDisplay could not be found on object: 870970-basis:24389499,870970-basis:24050017",
    "Parse error: briefDisplay could not be found on object: 870970-basis:01138898",
    "Parse error: briefDisplay could not be found on object: 870970-basis:29843511",
    "Parse error: briefDisplay could not be found on object: 870970-basis:06031390",
    "Parse error: briefDisplay could not be found on object: 870970-basis:26930642,870970-basis:53405568",
    "Parse error: briefDisplay could not be found on object: 870970-basis:28446594",
    "Parse error: briefDisplay could not be found on object: 870970-basis:28552408"
  ]
}

**Comment by BettinaAndersen** [comment]
Der er også set problemer ved søgning på andet end serier, som minder om problematikken med de "tomme" poster. Se nedenstående søgning på Harry Potter:
![image](https://user-images.githubusercontent.com/28528078/36677910-ae4b476e-1b0f-11e8-8c15-b91c345171d0.png)

**Comment by KiraH** [comment]
Der er lavet rettelser og alle ovenstående eksempler virker nu som de skal. Jeg lukker denne.
