### ISSUE TITLE
iPhone 5s - Læsebevis - jeg får en 500 fejl (ups du har ramt en side der ikke findes)

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#74]
Ved klik på Læsebevis i Min Profil: Ved klik får jeg en 500 fejl – ups du har ramt en side der ikke findes…

**Comment by lho** [comment]
får fejlen på https://biblo-dev.demo.dbc.dk/

**Comment by jacobandresen** [comment]
Jeg tænker at den her er relateret til #49

**Comment by lho** [comment]
I dag får jeg ikke Ups-fejlen

**Comment by AndersFriisBrodsgaard** [comment]
Vi har ikke fået fejlen siden, så jeg lukker.
