### ISSUE TITLE
Beskær værktitel ved visning af anmeldelse i indlæg

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#740]
Se fx https://biblo.dk/grupper/14
Titlen må ikke være længere end 5 linier (så det passer med forsidebilledets størrelse)

![2018-03-01_15-04-35_fejl i vedhaeftet anmeldelse](https://user-images.githubusercontent.com/18284484/36854999-c4571dfc-1d72-11e8-9448-3b0f17e4c1e9.jpg)

**Comment by KiraH** [comment]
testet OK
