### ISSUE TITLE
Udtræk af brugerstatistik for biblo

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#749]
Biblo vil gerne have et udtræk af data, så de kan se, hvor mange brugere, der er for de enkelte biblioteker. Det kan laves som fx et dump i en .csv-fil.

**Comment by BettinaAndersen** [comment]
Kan der sættes et job op der høster data fra community servicens api?

**Comment by AndersFriisBrodsgaard** [comment]
Det blev lavet et dump, så Biblo har fået de data, der skulle bruges i denne omgang. 
Lukker.
