### ISSUE TITLE
iPhone 5s - Profil - indlæg ligger dobbelt som både kommentar og som indlæg

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#76]
Under Min profil: Et indlæg jeg skrev i min egen gruppe ligger dobbelt både som Kommentar og som Indlæg

**Comment by hyatt03** [comment]
@lho Skrev du en kommentar til det indlæg?

**Comment by lho** [comment]
Det har rettet sig? - profil indhold ser ok ud nu

**Comment by hyatt03** [comment]
Ok.
