### ISSUE TITLE
Tripple-poster??

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#761]
Det ligner det samme materiale ligger der 3 gange? 
https://biblo.dk/materiale/870970-basis:27427847
https://biblo.dk/materiale/870970-basis:27259294
https://biblo.dk/materiale/870970-basis:27427863

Eller er det blot flere materialer i serien, som hedder det samme?

**Comment by kfudbc** [comment]
Det ser ud til at det er dvd 4, 1 og 5. Står under "mere info"

**Comment by BettinaAndersen** [comment]
Serie med samme Titel. Lukkes.
