### ISSUE TITLE
Sletning af profil 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#763]
Det skal være muligt for en bruger at slette sin profil.
Profildata skal slettes samt indlæg, anmeldelser, kommentarer, likes og grupper man følger.

Sletning skal ske helt - ikke bare slettemarkering.

Brugeren skal spørges om grupperne skal overføres eller slettes (#765)

**Acceptkriterie :** 
Under rediger profil skal der være en knap til at slette sin profil. 
Hvis man har oprettet grupper, skal brugeren spørges om grupperne skal slettes eller overføres til en anden ejer (Hvilken bruger skal kunne konfigureres). 
Når man sletter en profil, sletter alle brugerens indlæg, kommentarer, likes, grupper og anmeldelser.

**Comment by vibjerg** [comment]
Det meste af dette skal løses i biblos community service. Der er oprettet https://github.com/DBCDK/dbc-community-service/issues/91.

**Comment by AndersFriisBrodsgaard** [comment]
Feedback:

Når jeg sletter min testprofil og overfører ejerskab en min gruppe til en moderator, står der 0 følgere ud for gruppen på gruppeoversigtssiden, mens jeg stadig står som ejer inde på gruppesiden og som eneste følger.
Efter overførsel af en gruppe, hvor kun jeg er følger, skal der være én følger, dvs. den profil, som gruppen er overdraget til. Og min profil skal ikke optræde længere med billede eller lign.

**Comment by AndersFriisBrodsgaard** [comment]
Ved sletning af profil, skal cache af gruppesiderne invalideres, for de grupper, der overføres til en moderator.

**Comment by AndersFriisBrodsgaard** [comment]
Ved sletning af grupper, skal elastic search have tømt cachen, så grupperne ikke længere kan søges frem og der heller ikke laves suggestions på dem.
