### ISSUE TITLE
Sletning af data: Indlæg, kommentarer og anmeldelser

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#764]
Når brugeren sletter indlæg, kommentarer og anmeldelser, skal disse data slettes helt (, ikke bare slettemarkeres). Dette gælder også hvis brugeren sletter sin profil

Acceptkriterie: Slettede indlæg og kommentarer skal slettes helt i Community Servicen.

**Comment by vibjerg** [comment]
Alle data bliver slettet med #763. Der mangler stadig at sikre at data bliver slettet helt, når man slette et enkelt indlæg.
