### ISSUE TITLE
Slet af data skal gemmes i loggen

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#769]
Som resultat af GDPR skal data kunne slettes helt. Samtidig er der brug for at kunne finde slettede data i en periode efter, såfremt der kommer en anmeldelse (via Biblo konsortiet). 
Det forventes at løsningen er at gemme slettede data i loggen - som så slettes helt sammen med loggen efter x antal dage.

**Comment by vibjerg** [comment]
Er løst med https://github.com/DBCDK/dbc-community-service/issues/97
