### ISSUE TITLE
iPhone 5s - dev-sitet - Ved klik på Velkommen til biblo.dk havner jeg på driftssite

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#77]
https://biblo-dev.demo.dbc.dk/ - når jeg på biblo-dev klikker på Velkommen til biblo.dk, så havner jeg på driftssiden, uden at jeg lagde mærke til det i første omgang. Det betød at jeg kom til at oprette en gruppe i drift!)

**Comment by AndersFriisBrodsgaard** [comment]
Det har noget at gøre med det indhold, der hentes fra Amazon, som har absolutte links til driftsitet.
