### ISSUE TITLE
Ved opret anmeldelse med profil uden bibliotek, skal der kun spørges efter bibliotek

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#774]
Når en bruger med en profil uden bibliotek vil skrive en anmeldelse, skal han vælge et bibliotek, men han skal ikke udfylde lånernr eller pinkode. Derfor skal de to felter ikke være synlige i grænsefladen. 

Mange børn har ikke eller kan ikke huske deres lånerkortnr., men de skal have lov til at skrive en anmeldelse alligevel, så længe vi ved, hvilket bibliotek de tilhører. 

Relaterer sig til #643 som er løst, men er for streng mht. hvilke oplysninger, brugeren skal afgive.

**Comment by KiraH** [comment]
Jeg lukker den. Har ikke en profil uden bibliotek at teste med.

**Comment by KiraH** [comment]
Nu er den også testet og det virker som det skal.
