### ISSUE TITLE
Får beskeden "Du kan desværre ikke låne denne bog" selv om bogen findes i bibliotekets katalog

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#778]
![img_1930](https://user-images.githubusercontent.com/18284484/38957328-95ba76de-435a-11e8-9716-f063ca38d849.PNG)
PID: 870970-basis:54043465
Forsøgt lånt ca kl. 20.30 og igen kl. 22.52 onsdag d. 18. maj

Har oplevet det nogle gange på det seneste og har hørt fra andre, at de oplever det samme.

**Comment by BettinaAndersen** [comment]
løsning synes at være at opgradere til højere version af DÅP, se #783

**Comment by vibjerg** [comment]
Det er muligt at låne den nu efter opgradering. Har testet på københavn og frederiksberg bibliotek. Bør også lige testes med et mindre bibliotek. Måske @AndersFriisBrodsgaard kan gøre det?

**Comment by AndersFriisBrodsgaard** [comment]
Virker som det skal på demo, yes!
Er det rullet på drift? Jeg får nemlig hvid side, når jeg vil bestille den der.

**Comment by BettinaAndersen** [comment]
Jeg får ingen hvid side -alt går godt - men havde jo heller ikke problemet til at starte med, da den godt kan lånes på mit bibliotek.

**Comment by AndersFriisBrodsgaard** [comment]
Fik hvid side pga. manglende bibliotek i min profil. Med korrekt udfyldt profil virker det som det skal.
Lukker.
