### ISSUE TITLE
To udgaver af samme bog vises ikke sammen

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#779]
To udgaver af "Percy jackson og titanens forbandelse" vises som to hits i søgeresultatet. De bør vises som et samlet hit i søgeresultatet
https://biblo.dk/find?q=percy%20jackson%20og%20titanens%20forbandelse&grupper=0&emneord=&materialer=

https://biblo.dk/materiale/870970-basis:51669908
https://biblo.dk/materiale/870970-basis:54043465

Muligvis er det et problem med værkmatch?

**Comment by BettinaAndersen** [comment]
Fikses måske ved #783

**Comment by fvsdbc** [comment]
Er ikke fikset med v3
De tilhører hver sit værk, så måske er det DATA der skal høres.
http://introspect.corepo.cisterne.mcp1.dbc.dk/?tab=Search&tree=unit:30172447&pid=unit:30172447&selected=unit:30172447&header=pid&header=title&query=870970-basis:54043465&limit=20
og
http://introspect.corepo.cisterne.mcp1.dbc.dk/?tab=Search&tree=unit:1793644&pid=unit:1793644&selected=unit:1793644&header=pid&header=title&query=870970-basis:51669908&limit=20

**Comment by BettinaAndersen** [comment]
Lukkes da dette er et værkmatch-problem som er givet videre.
