### ISSUE TITLE
iPhone 5s - Grupper - jeg kan ikke slette egne indlæg?

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#78]

**Comment by AndersFriisBrodsgaard** [comment]
Virker knappen ikke eller er der ikke nogen "Slet"-knap?

**Comment by lho** [comment]
Der er ingen Slet-knap. Skal man som bruger ikke kunne fortryde?

**Comment by AndersFriisBrodsgaard** [comment]
OK. 
Pt. kan man godt slette indlæg, men ikke kommentarer. Er det et indlæg, der ikke har slet-knap eller er det en kommentar?

**Comment by lho** [comment]
Det er lidt mystisk - der er en sletteknap, men indlæg er tomt, og når jeg alligevel prøver at slette det tomme indlæg, ved at klikke på Slet, så starter en spinner, men der sker intet. 
Jeg tror det har forbindelse til sagen: iPhone 5s - Profil - indlæg ligger dobbelt som både kommentar og som indlæg #76

**Comment by AndersFriisBrodsgaard** [comment]
Lukker.
