### ISSUE TITLE
Opgrader til openplatform v.3

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#783]
I v.1 af OpenPlatform er orderPossible og willLend lagt sammen. Det betyder, at man ikke kan lave fjernlån (orderPossible), hvis ens eget biblioteket ikke har materialet (willLend). 

Dette er rettet i openPlatform v.2 og efterfølgende versioner. Derfor er der behov for at opgradere.

**Comment by BettinaAndersen** [comment]
Hvorfor ser vi først dette nu?
Biblo skal opgraderes til version 3. Giver ikke mening at opgradere til version 2.

**Comment by BettinaAndersen** [comment]
Er rullet ud. Lukker issuet.
