### ISSUE TITLE
Gruppe-ikon har forkert størrelse på gruppe-siden

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#793]
Ikonerne ud for gruppenavnene på /grupper er for små. De skal skaleres 50 % op og placeres på linie med gruppenavnet
Se https://biblo.dk/grupper

![screenshot 2018-06-01 13 25 05](https://user-images.githubusercontent.com/18284484/40838732-cff75b98-659f-11e8-950c-bf1f1b4fb05b.png)

**Comment by BettinaAndersen** [comment]
Fixed
