### ISSUE TITLE
Udskift automatisk load af flere værker med vis flere-knap på Best rated works-widget i mobilvisning

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#795]
https://biblo.dk/boger

Der er angivet i biblo admin, at der skal vises 20 bøger som default i widget'en, og det fungerer på desktop. Men i mobilvisningen hentes der løbende flere bøger ind, uden at brugeren skal klikke på "Vis flere". Det gør det svært at komme videre til indhold længere nede på siden, da der er anmeldelser af måske 10000 bøger...

Widgeten skal laves om til en slider.

**Comment by BettinaAndersen** [comment]
Fixed
