### ISSUE TITLE
Vis 2 værker bredden i Best rated works-widget i mobilvisning

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#796]
Pt vises der kun en værk pr. række i best rated works-widget'en i mobilvisning, se dump. Der skal vises to.

![screenshot 2018-06-01 14 24 54](https://user-images.githubusercontent.com/18284484/40840575-95743ac4-65a7-11e8-96e0-842b803d883c.png)

![screenshot 2018-06-01 14 24 05](https://user-images.githubusercontent.com/18284484/40840587-99fef390-65a7-11e8-9c52-83b4121965e6.png)

**Comment by AndersFriisBrodsgaard** [comment]
Vi er gået over til at denne widget vises som et bånd, der skal swipes, super. Jeg vil dog stadig gerne have, at der automatisk loades flere værker, når brugeren når til slutningen af båndet, da der er nærmest uendeligt mange værker at vise.

**Comment by BettinaAndersen** [comment]
Synes jeg har set denne til demo?

**Comment by AndersFriisBrodsgaard** [comment]
Yes, den er done.
