### ISSUE TITLE
Kan ikke lukke/fortryde tomt anmeldelsesvindue

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#80]
Jeg åbner anmeldelsesvinduet, men fortryder. Klikker ok, men får at vide at jeg mangler at udfylde. Man skal vel kunne fortryde/lukke tomt anmeldelsesvindue..?

**Comment by AndersFriisBrodsgaard** [comment]
Man kan klikke på "Lav en anmeldelse" igen, så skjules inputfelt mv. igen. Der bør dog rettes på teksten på knappen.

**Comment by Mariannedybkjaer** [comment]
det fandt jeg ud af på et tidspunkt. Men kun ved et tilfælde. Kan man ikke bare have et lille x i feltet?

**Comment by AndersFriisBrodsgaard** [comment]
Oprettet i Scrumdo
