### ISSUE TITLE
Indsæt anden tekst i modalvindue ved sletning af profil. 

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo#804]
Flyttet fra #799, da vi afventer tekstoplæg fra Biblo.

**Comment by AndersFriisBrodsgaard** [comment]
![flow-design-slet-profil-0](https://user-images.githubusercontent.com/18284484/41660697-1c374fe8-749d-11e8-800d-33d88d15fad4.png)
![flow-design-slet-profil-1](https://user-images.githubusercontent.com/18284484/41660698-1c545e12-749d-11e8-828c-a7af4919e5eb.png)

**Comment by AndersFriisBrodsgaard** [comment]
Som en lille kuriositet, vil vi gerne have den lysegrå tekst i andet billede til at være rød (samme farve som overskriften)
