### ISSUE TITLE
IE11 - Profil - mit profilbillede vises på den forkerte led

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#81]
på iPhone vises profilbillede korrekt
https://biblo-dev.demo.dbc.dk/

**Comment by jacobandresen** [comment]
Det kan være relateret til et midlertidigt problem. Gider du prøve igen? Vær opmærksom på at billedbehandlingen kører på serveren og kan tage lang tid at afslutte. Prøv gerne at vente et minuts tid for at se om det hjælper.

**Comment by lho** [comment]
hahaha - nu er mit profilfoto (i det lille format) på hovedet i IE11.
jeg skiftede mit profilfoto ud (tog et nyt foto på iPhone holdt på den brede led). 
Vises stadig ok på mobilen.
biblo-dev.demo.dbc.dk

**Comment by jacobandresen** [comment]
sjovt.  Jeg har genskabt problemet ved at tage billedet med  iphone 6 . Der vises begge billeder fint.  Når jeg viser min profil-side i chrome på min computer , så vendes billedet om i den store udgave af billedet  - men ikke i den lille.  Jeg kigger på det

**Comment by jacobandresen** [comment]
Hej Laura. Kan du  huske noget om tidspunktet for hvornår du uploaded billedet? Så kan jeg kigge I loggen herovre. .. Jeg kan ikke genskabe problemet igen her. Giv gerne lyd, hvis du kan genskabe problemet .. og gerne et tidspunkt.

**Comment by jacobandresen** [comment]
genskabt biblo-dev.demo.dbc.dk kl 14:59 . medium profil billeder bliver ikke roteret

**Comment by jacobandresen** [comment]
Problemet ser ud til at ske oftest når kamera-retningen er ind med brugeren på telefonen og biblo-dev bliver brugt (lige nu)

**Comment by jacobandresen** [comment]
Problemet optræder ikke i produktion  efter deploy lige nu. ( Har lige testet sammen med Laura)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
