### ISSUE TITLE
Suggest på materialer virker ikke

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#812]
Man får pt. kun suggestions på grupper. Søgning giver resultater, som den skal. Er suggesteren for Biblo mon lukket ned? Eller trænger den til en genstart. biblo.dk/howru siger "OK"
"Kapt" giver ikke Kaptajn underhyler
"Hest" giver ikke noget
"Harr" giver ikke noget
![screenshot 2018-06-21 18 08 00](https://user-images.githubusercontent.com/18284484/41731456-c19107ea-757e-11e8-9a9a-05288d8142c4.png)

**Comment by vibjerg** [comment]
Der ser ud til at være problemer med http://xptest.dbc.dk/ms/entity-suggest/v1/

**Comment by AndersFriisBrodsgaard** [comment]
Servicen er oppe igen.
