### ISSUE TITLE
Ændring af profiloprettelse - og nu med hjælpetekster

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#838]
Det ønskes at gøres mere tydeligt hvilke dele der skal udfyldes i forbindelse med profiloprettelse samt hvilke der kan vente. Derfor ønskes profiloprettelse-skærmen ændret til følgende:
![image](https://user-images.githubusercontent.com/28528078/42379519-2a51f192-812b-11e8-9ba7-53aa7d44fb4d.png)

Lånernummer og pinkode skal ikke længere kunne ses i profilen.

Herudover ønskes muligheden for at kunne klikke på et "hjælpelink" for hvert udfylningspunkt. Ved klik på et sådant link skal der åbnes et modal-vindue med hjælpetekst.

På mobil skal hjælpeteksten blot være "Hvorfor?" for alle punkter.

Der skal desuden være link i bunden til en side der forklarer Biblos datapolitik, som skal åbnes i en ny fane. Denne url mangler at blive leveret af Biblo-projektet, hvor dette er oprettet som separat issue: 
#846 
Hjælpetekster ses i næste kommentar.

**Comment by BettinaAndersen** [comment]
Hjælpetekster:
Tekster til opret profil på biblo.dk:

Hvorfor kan jeg uploade et profilbillede?
Et profilbillede er med til at gøre din profil mere personlig. Nogle har et billede af deres kæledyr, andre et billede af dem selv og andre igen noget fra deres yndlingsbog eller –spil. Det er ikke tilladt at uploade billeder af andre personer end sig selv, billeder, der er beskyttet af copyright eller billeder, der kan støde andre. Biblo.dks moderatorer kan slette og redigere alle profilbilleder på biblo.dk. Hvis du ikke uploader et profilbillede, sætter systemet et standard-billede ind. 

Skriv et profilnavn – Hvorfor skal jeg det?
Alle profiler på biblo.dk skal have sit eget navn, så man kan skelne profilerne fra hinanden. Mange finder på sjove navne. Du kan altid ændre dit profilnavn, hvis du bliver træt af det gamle. Bare log ind på biblo.dk, tryk på din profil, dernæst på den lille blyant og skriv så et nyt navn. Husk at trykke på gem nederst på siden. Et profilnavn må ikke støde nogen, det må ikke være dit Unilogin eller cpr-nummer, adresse eller lignende. Du må ikke bruge en anden persons navn, men du må gerne bruge dit rigtige navn.

Vælg dit bibliotek – Hvorfor skal jeg det?
Biblo.dk er lavet af folkebibliotekerne og det er vigtigt for os at vide, hvilket bibliotek, du hører til. For eksempel skal du hente din præmie på dit bibliotek, hvis du vinder i en af de mange konkurrencer. Bibliotekerne laver også statistik på hvor mange børn fra deres kommune, der er aktive på biblo.dk. Du kan også låne bøger via biblo.dk og det er nemmere for dig, når dit bibliotek er valgt.

Dit rigtige navn – Hvorfor kan jeg vælge det?
Denne oplysning kan kun ses af moderatorerne fra biblo.dk. Hvis vi kender dit rigtige navn, er det nemmere at give dig den rigtige besked, hvis du har vundet en præmie i en konkurrence på biblo.dk. 

Mobil (din eller dine forældres) – Hvorfor kan jeg vælge det?
Hvis du har vundet i en af konkurrencerne på biblo.dk, så har vi brug for at kontakte dig. Vi har kun mulighed for at kontakte dig, hvis du har skrevet et telefonnummer eller en e-mailadresse. Helst begge dele, så chancerne for at du får beskeden fra os bliver større. Biblo.dk deler aldrig disse oplysninger med andre end det bibliotek, du er tilknyttet og som skal give dig den præmie, du måtte vinde. Ingen andre end biblo.dks moderatorer kan se dit mobilnummer.

E-mail (din eller dine forældres) – Hvorfor kan jeg vælge det?
Hvis du har vundet i en af konkurrencerne på biblo.dk, så har vi brug for at kontakte dig. Vi har kun mulighed for at kontakte dig, hvis du har skrevet et telefonnummer eller en e-mailadresse. Helst begge dele, så chancerne for at du får beskeden fra os bliver større. Biblo.dk deler aldrig disse oplysninger med andre end det bibliotek, du er tilknyttet og som skal give dig den præmie, du måtte vinde. Ingen andre end biblo.dks moderatorer kan se din e-mail.

Det år du blev født – Hvorfor kan jeg vælge det?
Nogle konkurrencer på biblo.dk er kun for bestemte aldersgrupper. Vi har derfor brug for at se, om du er gammel eller ung nok til at deltage i konkurrencen. Biblo.dk bruger også denne information til at lave statistik over, hvilken alder, brugerne på biblo.dk har. Udover moderatorerne på biblo.dk kan ingen se din alder.

Beskriv dig selv – Hvorfor kan jeg vælge det?
Du har mulighed for at skrive lidt om dig selv. Dette vil andre på biblo.dk kunne se, når de trykker på din profil. Mange skriver, at de elsker bøger, heste, fodbold eller Minecraft. Andre skriver, hvilken by de bor i eller, hvor gamle de er. Man må ikke skrive sit Unilogin, cpr-nummer, adresse eller andet, der fortæller præcist, hvem man er. Man må heller ikke skrive noget, som kan støde andre eller noget, der linker til andre sider. Moderatorerne på biblo.dk kan ændre i jeres beskrivelser af jer selv.

Her kan du læse mere om hvordan vi passer på dine data på biblo.dk

**Comment by BettinaAndersen** [comment]
Mindre rettelse fra Biblo-gruppen:
Alle de steder, hvor der står ”moderator” skal der i stedet stå: "moderator (voksne admins)"
Hvorfor kan jeg uploade et profilbillede?
Et profilbillede er med til at gøre din profil mere personlig. Nogle har et billede af deres kæledyr, andre et billede af dem selv og andre igen noget fra deres yndlingsbog eller –spil. Det er ikke tilladt at uploade billeder af andre personer end sig selv, billeder, der er beskyttet af copyright eller billeder, der kan støde andre. Biblo.dks moderatorer kan slette og redigere alle profilbilleder på biblo.dk. Hvis du ikke uploader et profilbillede, sætter systemet et standard-billede ind.
Skriv et profilnavn – Hvorfor skal jeg det?
Alle profiler på biblo.dk skal have sit eget navn, så man kan skelne profilerne fra hinanden. Mange finder på sjove navne. Du kan altid ændre dit profilnavn, hvis du bliver træt af det gamle. Bare log ind på biblo.dk, tryk på din profil, dernæst på den lille blyant og skriv så et nyt navn. Husk at trykke på gem nederst på siden. Et profilnavn må ikke støde nogen, det må ikke være dit Unilogin eller cpr-nummer, adresse eller lignende. Du må ikke bruge en anden persons navn, men du må gerne bruge dit rigtige navn.
Vælg dit bibliotek – Hvorfor skal jeg det?
Biblo.dk er lavet af folkebibliotekerne og det er vigtigt for os at vide, hvilket bibliotek, du hører til. For eksempel skal du hente din præmie på dit bibliotek, hvis du vinder i en af de mange konkurrencer. Bibliotekerne laver også statistik på hvor mange børn fra deres kommune, der er aktive på biblo.dk. Du kan også låne bøger via biblo.dk og det er nemmere for dig, når dit bibliotek er valgt.
Dit rigtige navn – Hvorfor kan jeg vælge det?
Denne oplysning kan kun ses af moderatorerne fra biblo.dk. Hvis vi kender dit rigtige navn, er det nemmere at give dig den rigtige besked, hvis du har vundet en præmie i en konkurrence på biblo.dk.
Mobil (din eller dine forældres) – Hvorfor kan jeg vælge det?
Hvis du har vundet i en af konkurrencerne på biblo.dk, så har vi brug for at kontakte dig. Vi har kun mulighed for at kontakte dig, hvis du har skrevet et telefonnummer eller en e-mailadresse. Helst begge dele, så chancerne for at du får beskeden fra os bliver større. Biblo.dk deler aldrig disse oplysninger med andre end det bibliotek, du er tilknyttet og som skal give dig den præmie, du måtte vinde. Ingen andre end biblo.dks moderatorer kan se dit mobilnummer.
E-mail (din eller dine forældres) – Hvorfor kan jeg vælge det?
Hvis du har vundet i en af konkurrencerne på biblo.dk, så har vi brug for at kontakte dig. Vi har kun mulighed for at kontakte dig, hvis du har skrevet et telefonnummer eller en e-mailadresse. Helst begge dele, så chancerne for at du får beskeden fra os bliver større. Biblo.dk deler aldrig disse oplysninger med andre end det bibliotek, du er tilknyttet og som skal give dig den præmie, du måtte vinde. Ingen andre end biblo.dks moderatorer kan se din e-mail.
Det år du blev født – Hvorfor kan jeg vælge det?
Nogle konkurrencer på biblo.dk er kun for bestemte aldersgrupper. Vi har derfor brug for at se, om du er gammel eller ung nok til at deltage i konkurrencen. Biblo.dk bruger også denne information til at lave statistik over, hvilken alder, brugerne på biblo.dk har. Udover moderatorerne på biblo.dk kan ingen se din alder.
Beskriv dig selv – Hvorfor kan jeg vælge det?
Du har mulighed for at skrive lidt om dig selv. Dette vil andre på biblo.dk kunne se, når de trykker på din profil. Mange skriver, at de elsker bøger, heste, fodbold eller Minecraft. Andre skriver, hvilken by de bor i eller, hvor gamle de er. Man må ikke skrive sit Unilogin, cpr-nummer, adresse eller andet, der fortæller præcist, hvem man er. Man må heller ikke skrive noget, som kan støde andre eller noget, der linker til andre sider. Moderatorerne på biblo.dk kan ændre i jeres beskrivelser af jer selv.

**Comment by AndersFriisBrodsgaard** [comment]
Kommentarer ved test:
- Når man klikker på "Hvorfor"-linksene på iOS, vises teksten korrekt i overlay, men tastaturet vises også, selv om der ikke er noget aktivt felt, man kan skrive i. Der skal ikke vises tastatur.
- Lidt mere afstand mellem de to områder "**skal udfylde**" og "**behøver du ikke at udfylde**", så de er nemmere at skelne fra hinanden. Fx 2rem.
- Den nye tekst på Opret-knappen nederst skal kun gælde for opret-visningen. Ved redigering af en eksisterende profil, skal der stå "Gem min profil"
