### ISSUE TITLE
I søgefeltet står der kun 3 mattyper

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#84]
Man kan angiveligt kun søge på bøger, film og spil. Måske er det flueknepperi, men kan man forestille sig, at nogen vil tro, at man ikke kan søge musik?

**Comment by AndersFriisBrodsgaard** [comment]
@Mariannedybkjaer Der skal være knapper til bog, lydbog, film, musik, spil. Og et nulstil-link.
Hvilket device er du på?

**Comment by Mariannedybkjaer** [comment]
Det er ikke knapper. Det er ledeteksten i søgefeltet

**Comment by AndersFriisBrodsgaard** [comment]
Ahh, OK.

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
