### ISSUE TITLE
Tidligere likes er væk - kan de genskabes?

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#848]
Alle likes i grupperne på biblo.dk tilsyneladende er forsvundet. Biblo-gruppen har prøvet at like nogle ting i dag, og de likes står der (det er i gruppen Fun Facts), men alle andre likes synes at være forsvundet. 

Om muligt skal de tidligere likes genskabes. Hvis ikke muligt, skal vi i det mindste kunne forklare hvordan dette kan være sket.

**Comment by vibjerg** [comment]
Likes fra før 27. juli er genskabt. Der kan være nogle i løbet af sommerferien, som er forsvundet, men det er ikke til at sige og de kan ikke genskabes. Fejlen er opstået i forbindelse med udrulning af sletning af profil.  Er blevet løst i forbindelse med https://github.com/DBCDK/dbc-community-service/issues/111
