### ISSUE TITLE
Skriv anmeldelse-felt går i fuld sidebredde

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#85]
Inputboksen skal kun fylde bredden svarende til visningen af anmeldelserne. Dvs. ca. 2/3 af siden bredde.
![screenshot 2016-06-01 15 34 08](https://cloud.githubusercontent.com/assets/18284484/15711514/9b236f04-280e-11e6-9dc5-28c13be33ca5.png)

**Comment by jacobandresen** [comment]
Skriv anmeldeses feltet fylder nu det samme som listen af anmeldelser (2/3)

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
