### ISSUE TITLE
Få vist alle anmeldelser som knytter sig til et bind i et flerbindsværk

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo#856]
Ifm. #853 har vi ændret på hentning af anmeldelser, så vi kun henter anmeldelser ud på en primær pid, og betyder at hvis man f.eks. laver en anmeldelse på en lydbog, så kommer de ikke med på oversigten på værksiden.

**Comment by BettinaAndersen** [comment]
Testet ok
