### ISSUE TITLE
Når man filtrerer på lydbøger, får man ikke en serievisning af flerbindsværker på værksiden

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/biblo#857]
Hvis man f.eks. søger på krigerkattene og filterer på lydbøger (https://biblo.dk/find?q=krigerkattene&grupper=0&emneord=&materialer=audiobook) Så får man ikke en serievisning: 

https://biblo.dk/materiale/870970-basis:29227365

I modsætning til den normale visning af krigerkattene:

https://biblo.dk/materiale/870970-basis:52796636

**Comment by BettinaAndersen** [comment]
Testet ok
