### ISSUE TITLE
Udtræk af statistik for sommerbogen

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#870]
Der skal laves 2 udtræk af data
1. Udtræk af reviews fra og med 10. juni til og med 25. august. Der skal kun udtrækkes reviews for materialer af typerne "Book", "Literature", "Audiobook" og "Other"
2. Udtræk af anmeldte materialer (PID'er) incl. antal anmeldelser for det enkelte materiale og sorteret efter antallet af reviews.

Udtrækkenes leveres i csv-filer.

**Comment by BettinaAndersen** [comment]
Sendt til Biblo
