### ISSUE TITLE
HowRU endpoint skal ikke kalde OpenAgency

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/biblo#876]
Det antages at Biblo benytter OpenAgency via DÅP og derfor skal HowRU ændres til ikke at foretage direkte kald til OpenAgency. 
Dette skal naturligvis lige tjekkes inden det fjernes.

**Comment by vibjerg** [comment]
Det ser ud til at vi stadig benytter openagency direkte. Det skyldes muligvis at vi benytter noget funktionalitet, som ikke findes i DÅP. Det bør selvfølgelig undersøges nærmere.  Har oprettet (#880) og lukker derfor denne.
