### ISSUE TITLE
ikoner forskudt ved søgning i crome 

### ISSUE THREAD

**Issue by KiraH** [DBCDK/biblo#90]
![soening](https://cloud.githubusercontent.com/assets/355018/15736941/69ba5b54-28a3-11e6-95d8-486dd1415fdc.png)

https://biblo.demo.dbc.dk/find?q=danmark&emneord=&materialer=

**Comment by hyatt03** [comment]
Det er browser cache, refresh et par gange :)

**Comment by KiraH** [comment]
Du har ret
