### ISSUE TITLE
iPhone 5s - Læsebevis - der optræder en dato (03-05-2016) under titlerne

### ISSUE THREAD

**Issue by lho** [DBCDK/biblo#93]
ved ikke om den skal være der, eller om det er en kendt ting

**Comment by AndersFriisBrodsgaard** [comment]
Det er for at bibliotekarerne kan se, hvornår børnene har lavet anmeldelsen - altså indenfor Sommerbogen-perioden.

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
