### ISSUE TITLE
Ville være smart med numerisk tastatur ved nummeroplysninger i profil

### ISSUE THREAD

**Issue by Mariannedybkjaer** [DBCDK/biblo#95]
Når man er på en mobil, ville det være smart at man får nummertastatur v CPR og pinkode - ligesom v mobilnr.

**Comment by hrmoller** [comment]
Det er en generel forbedring på alle håndholdte devices, der ikke bare gælder HTC.

**Comment by AndersFriisBrodsgaard** [comment]
Oprettes i ScrumDo
