### ISSUE TITLE
Styling af "Mere info"-området på værkside

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/biblo#96]
På desktop skal "Mere info"-området fylde hele bredden af højrespalten. Se nuværende styling i vedhæftede dump
På mobil skal det fylde hele bredden på siden, under evt. anmeldelser.
![screenshot 2016-06-02 14 54 40](https://cloud.githubusercontent.com/assets/18284484/15745699/842f2f48-28d3-11e6-9f2e-77c2c055cc28.png)

**Comment by AndersFriisBrodsgaard** [comment]
Og de specifikke materialetyper (incl. ikoner) skal fylde hele bredden for hhv. højrespalte (desktop) og hele siden (mobil)

**Comment by KiraH** [comment]
testet OK
