### ISSUE TITLE
Det er ikke muligt at bestille bøger fra anmeldeses sider.

### ISSUE THREAD

**Issue by hyatt03** [DBCDK/biblo#99]
Når man forsøger at bestille en bog fra en anmeldelsesside får man en fejlbesked der beder en om at vælge et nyt bibliotek, dette er da biblioteksinfo fra openagency ikke bliver sat på profilobjektet og dermed ikke kan tilgås.

Se BorrowButton.component.js linje 224 for mere info.

**Comment by AndersFriisBrodsgaard** [comment]
OK. Lukker.
